DROP TABLE DATA_MIG.ASSAY_CONTEXT_MEASURE_DUP CASCADE CONSTRAINTS
/
DROP TABLE DATA_MIG.ASSAY_CONTEXT_DUP CASCADE CONSTRAINTS
/
DROP TABLE DATA_MIG.SOUTHERN_RESULT_MAP CASCADE CONSTRAINTS
/
DROP TABLE DATA_MIG.TEMP_CONTEXT_ITEM CASCADE CONSTRAINTS
/
DROP TABLE DATA_MIG.ASSAY_CONTEXT_ITEM_DUP CASCADE CONSTRAINTS
/

DROP TABLE DATA_MIG.ASSAY_CONTEXT_MEASURE_DUP CASCADE CONSTRAINTS
/
DROP TABLE DATA_MIG.ASSAY_CONTEXT_DUP CASCADE CONSTRAINTS
/
DROP TABLE DATA_MIG.SOUTHERN_RESULT_MAP CASCADE CONSTRAINTS
/
DROP TABLE DATA_MIG.TEMP_CONTEXT_ITEM CASCADE CONSTRAINTS
/
DROP TABLE DATA_MIG.ASSAY_CONTEXT_ITEM_DUP CASCADE CONSTRAINTS
/


DROP VIEW DATA_MIG.ASSAY_ELEMENT
/
CREATE VIEW DATA_MIG.ASSAY_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE ELEMENT_ID in (select adt.ELEMENT_ID from ASSAY_DESCRIPTOR_TREE adt)
/
DROP VIEW DATA_MIG.BIOLOGY_ELEMENT
/
CREATE VIEW DATA_MIG.BIOLOGY_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select bdt.ELEMENT_ID from BIOLOGY_DESCRIPTOR_TREE bdt)
/
DROP VIEW DATA_MIG.INSTANCE_ELEMENT
/
CREATE VIEW DATA_MIG.INSTANCE_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select idt.ELEMENT_ID from INSTANCE_DESCRIPTOR_TREE idt)
/
DROP VIEW DATA_MIG.LABORATORY_ELEMENT
/
CREATE VIEW DATA_MIG.LABORATORY_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit_ID, BARD_URI, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT_ID, El.BARD_URI, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE ELEMENT_ID in (select LABORATORY_ID from LABORATORY_TREE)
/
DROP VIEW DATA_MIG.RESULT_TYPE_ELEMENT
/
CREATE VIEW DATA_MIG.RESULT_TYPE_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select RESULT_TYPE_ID from RESULT_TYPE_TREE)
/
DROP VIEW DATA_MIG.STAGE_ELEMENT
/
CREATE VIEW DATA_MIG.STAGE_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select STAGE_ID from STAGE_TREE)
/
DROP VIEW DATA_MIG.UNIT_ELEMENT
/
CREATE VIEW DATA_MIG.UNIT_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE ELEMENT_ID in (select UNIT_ID from UNIT_TREE)
/


DROP VIEW DATA_MIG.ASSAY_ELEMENT
/
CREATE VIEW DATA_MIG.ASSAY_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE ELEMENT_ID in (select adt.ELEMENT_ID from ASSAY_DESCRIPTOR_TREE adt)
/
DROP VIEW DATA_MIG.BIOLOGY_ELEMENT
/
CREATE VIEW DATA_MIG.BIOLOGY_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select bdt.ELEMENT_ID from BIOLOGY_DESCRIPTOR_TREE bdt)
/
DROP VIEW DATA_MIG.INSTANCE_ELEMENT
/
CREATE VIEW DATA_MIG.INSTANCE_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select idt.ELEMENT_ID from INSTANCE_DESCRIPTOR_TREE idt)
/
DROP VIEW DATA_MIG.LABORATORY_ELEMENT
/
CREATE VIEW DATA_MIG.LABORATORY_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit_ID, BARD_URI, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT_ID, El.BARD_URI, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE ELEMENT_ID in (select LABORATORY_ID from LABORATORY_TREE)
/
DROP VIEW DATA_MIG.RESULT_TYPE_ELEMENT
/
CREATE VIEW DATA_MIG.RESULT_TYPE_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select RESULT_TYPE_ID from RESULT_TYPE_TREE)
/
DROP VIEW DATA_MIG.STAGE_ELEMENT
/
CREATE VIEW DATA_MIG.STAGE_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select STAGE_ID from STAGE_TREE)
/
DROP VIEW DATA_MIG.UNIT_ELEMENT
/
CREATE VIEW DATA_MIG.UNIT_ELEMENT AS
SELECT El.ELEMENT_ID Element_ID, El.ELEMENT_STATUS Element_Status, El.LABEL Label, El.DESCRIPTION Description, El.ABBREVIATION Abbreviation, El.SYNONYMS Synonyms, El.UNIT_ID Unit_ID, El.BARD_URI BARD_URI, El.EXTERNAL_URL External_URL, El.READY_FOR_EXTRACTION ready_for_extraction, El.VERSION Version, El.DATE_CREATED Date_Created, El.LAST_UPDATED Last_Updated, El.MODIFIED_BY Modified_by
FROM ELEMENT El
WHERE ELEMENT_ID in (select UNIT_ID from UNIT_TREE)
/
