/*
 * File: app/view/AssayDetailTree.js
 * Date: Mon May 07 2012 05:59:18 GMT-0400 (EDT)
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BARD.view.AssayDetailTree', {
    extend: 'Ext.tree.Panel',
    alias: 'widget.assaydetailtree',

    title: 'Assay Detail',
    store: 'AssayDetailTreeStore',
    rootVisible: false,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            }
        });

        me.callParent(arguments);
    }

});