/*
 * File: app/view/CapApp.js
 * Date: Fri Apr 27 2012 16:25:13 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BARD.view.CapApp', {
    extend: 'Ext.container.Viewport',
    requires: [
        'BARD.view.AssayForm',
        'BARD.view.ResultTypesForm',
        'BARD.view.elementTree'
    ],

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    id: 'capTabPanel',
                    title: 'CAP Assay Definition',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'findAssayTab',
                            title: 'Find an Assay',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    height: 288,
                                    width: 894,
                                    title: 'All Assays',
                                    store: 'assayStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'id',
                                            text: 'ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'assayName',
                                            flex: 1,
                                            text: 'Assay Name'
                                        }
                                    ],
                                    listeners: {
                                        selectionchange: {
                                            fn: me.onGridpanelSelectionChange,
                                            scope: me
                                        }
                                    }
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            id: 'assayTab',
                            itemId: 'assayFormTab',
                            width: 983,
                            activeItem: '',
                            title: 'Extract Name, Description',
                            items: [
                                {
                                    xtype: 'assayform',
                                    id: 'assayForm'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Result Types (Measures)',
                            items: [
                                {
                                    xtype: 'resulttypesform'
                                }
                            ]
                        },
                        {
                            xtype: 'elementtree'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelSelectionChange: function(tablepanel, selections, options) {
        var tabs = Ext.getCmp("capTabPanel");
        var tab = Ext.getCmp('assayTab');
        var assayFormPanel = tab.getComponent('assayForm');
        assayFormPanel.getForm('form').loadRecord(selections[0]);
        tabs.setActiveTab(tab);

    }

});