/*
 * File: app/view/CapApp.js
 * Date: Wed May 02 2012 10:51:40 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BARD.view.CapApp', {
    extend: 'Ext.container.Viewport',
    requires: [
        'BARD.view.AssayForm',
        'BARD.view.ResultTypesForm',
        'BARD.view.elementTree'
    ],

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    title: 'CAP Assay Definition',
                    activeTab: 1,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Find an Assay',
                            items: [
                                {
                                    xtype: 'gridpanel',
                                    height: 288,
                                    width: 894,
                                    title: 'All Assays',
                                    forceFit: false,
                                    store: 'assayStore',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'id',
                                            text: 'ID'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            dataIndex: 'assayName',
                                            flex: 1,
                                            text: 'Assay Name'
                                        }
                                    ],
                                    listeners: {
                                        selectionchange: {
                                            fn: me.onGridpanelSelectionChange,
                                            scope: me
                                        }
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'toolbar',
                                            dock: 'top',
                                            items: [
                                                {
                                                    xtype: 'textfield',
                                                    width: 394,
                                                    name: 'SearchTextField',
                                                    fieldLabel: 'Search',
                                                    labelWidth: 70
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            width: 983,
                            title: 'Extract Name, Description',
                            items: [
                                {
                                    xtype: 'assayform',
                                    id: 'assayForm',
                                    url: 'api/assay'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Result Types (Measures)',
                            items: [
                                {
                                    xtype: 'resulttypesform'
                                }
                            ]
                        },
                        {
                            xtype: 'elementtree'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onGridpanelSelectionChange: function(tablepanel, selections, options) {
        var formPanel = Ext.get("assay-form");
        formPanel.getForm().loadRecord(records[0]);
    }

});