/*
 * File: app/view/ProjectForm.js
 * Date: Fri Apr 27 2012 13:00:13 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BARD.view.ProjectForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.projectform',

    layout: {
        type: 'absolute'
    },
    bodyPadding: 10,
    preventHeader: true,
    title: 'ProjectForm',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'combobox',
                    width: 500,
                    name: 'projectName',
                    fieldLabel: 'Project',
                    displayField: 'projectName',
                    store: 'ProjectDStore',
                    valueField: 'id'
                },
                {
                    xtype: 'combobox',
                    name: 'groupType',
                    fieldLabel: 'Type',
                    displayField: 'label',
                    store: 'groupTypeStore',
                    valueField: 'id',
                    x: 10,
                    y: 40
                },
                {
                    xtype: 'combobox',
                    name: 'stage',
                    fieldLabel: 'Stage',
                    displayField: 'stage',
                    store: 'StageStore',
                    valueField: 'id',
                    x: 10,
                    y: 70
                },
                {
                    xtype: 'gridpanel',
                    height: 150,
                    width: 510,
                    title: 'Other assays in this project:',
                    store: 'assayStore',
                    x: 10,
                    y: 120,
                    columns: [
                        {
                            xtype: 'gridcolumn',
                            width: 507,
                            dataIndex: 'string',
                            text: 'Assay Names'
                        }
                    ],
                    viewConfig: {

                    }
                },
                {
                    xtype: 'button',
                    width: 40,
                    text: 'Up',
                    x: 540,
                    y: 120
                },
                {
                    xtype: 'button',
                    text: 'Down',
                    x: 540,
                    y: 160
                },
                {
                    xtype: 'button',
                    text: 'Save',
                    x: 540,
                    y: 290
                },
                {
                    xtype: 'button',
                    text: 'Cancel',
                    x: 470,
                    y: 290
                }
            ]
        });

        me.callParent(arguments);
    }

});