ALTER TABLE ASSAY DROP CONSTRAINT CK_ASSAY_STATUS;

ALTER TABLE EXPERIMENT DROP CONSTRAINT CK_EXPERIMENT_STATUS;

ALTER TABLE PROJECT ADD PROJECT_STATUS VARCHAR2(10);

UPDATE PROJECT set project_status = 'Draft';

UPDATE EXPERIMENT set experiment_status = 'Draft' where experiment_status = 'Pending';

ALTER TABLE ASSAY ADD CONSTRAINT CK_ASSAY_STATUS CHECK (Assay_Status IN ('Draft', 'Approved', 'Retired')) ENABLE;

ALTER TABLE PROJECT ADD CONSTRAINT CK_PROJECT_STATUS CHECK (Project_Status IN ('Draft', 'Approved', 'Retired')) ENABLE;

ALTER TABLE EXPERIMENT ADD CONSTRAINT CK_EXPERIMENT_STATUS CHECK (EXPERIMENT_STATUS IN ('Draft', 'Approved', 'Retired')) ENABLE;
