UPDATE ASSAY SET LAST_UPDATED=SYSDATE WHERE LAST_UPDATED IS NULL;

UPDATE PROJECT SET LAST_UPDATED=SYSDATE WHERE LAST_UPDATED IS NULL;

UPDATE EXPERIMENT SET LAST_UPDATED=SYSDATE WHERE LAST_UPDATED IS NULL;

UPDATE ASSAY_DOCUMENT SET LAST_UPDATED=SYSDATE WHERE LAST_UPDATED IS NULL;

ALTER TABLE ASSAY MODIFY(LAST_UPDATED DEFAULT SYSDATE NOT NULL);

ALTER TABLE PROJECT MODIFY(LAST_UPDATED DEFAULT SYSDATE NOT NULL);

ALTER TABLE EXPERIMENT MODIFY(LAST_UPDATED DEFAULT SYSDATE NOT NULL );

ALTER TABLE ASSAY_DOCUMENT MODIFY(LAST_UPDATED DEFAULT SYSDATE NOT NULL );
