-- Standard Alter Table SQL

COMMENT ON COLUMN UNIT_CONVERSION.VERSION IS
''
;
ALTER TABLE ASSAY MODIFY(ASSAY_NAME  VARCHAR2(1000 CHAR))
;
COMMENT ON COLUMN ASSAY.VERSION IS
''
;
COMMENT ON COLUMN ASSAY_DOCUMENT.VERSION IS
''
;
COMMENT ON COLUMN ELEMENT.VERSION IS
''
;
COMMENT ON COLUMN EXPERIMENT.VERSION IS
''
;
ALTER TABLE EXTERNAL_REFERENCE DROP CONSTRAINT CK_PROJECT_EXPERIMENT_NULLS
;
COMMENT ON COLUMN EXTERNAL_REFERENCE.VERSION IS
''
;
COMMENT ON COLUMN EXTERNAL_SYSTEM.VERSION IS
''
;
COMMENT ON COLUMN MEASURE.VERSION IS
''
;
COMMENT ON COLUMN MEASURE_CONTEXT.VERSION IS
''
;
COMMENT ON COLUMN ONTOLOGY.VERSION IS
''
;
COMMENT ON COLUMN ONTOLOGY_ITEM.VERSION IS
''
;
ALTER TABLE PROJECT DROP CONSTRAINT CK_PROJECT_TYPE
;
COMMENT ON COLUMN PROJECT.VERSION IS
''
;
ALTER TABLE PROJECT ADD CONSTRAINT CK_PROJECT_TYPE
CHECK (GROUP_TYPE in ('Project', 'Probe Report', 'Campaign', 'Panel', 'Study'))
;
COMMENT ON COLUMN PROJECT_EXPERIMENT.VERSION IS
''
;
COMMENT ON COLUMN RESULT.VERSION IS
''
;
ALTER TABLE RESULT_HIERARCHY DROP CONSTRAINT FK_RESULT_HIERARCHY_RESULT
;
ALTER TABLE RESULT_HIERARCHY DROP CONSTRAINT FK_RESULT_HIERARCHY_RSLT_PRNT
;
COMMENT ON COLUMN RESULT_HIERARCHY.VERSION IS
''
;
COMMENT ON COLUMN SUBSTANCE.VERSION IS
''
;
COMMENT ON TABLE SUBSTANCE IS
'Substance is used a CACHE of data from PubChem.  This cache can be removed if we can be assured that availability and capacity (for API queries) of PubChem will support dynamic use.'
;
ALTER TABLE RESULT_HIERARCHY ADD CONSTRAINT FK_RESULT_HIERARCHY_RESULT
FOREIGN KEY (PARENT_RESULT_ID)
REFERENCES RESULT (RESULT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE RESULT_HIERARCHY ADD CONSTRAINT FK_RESULT_HIERARCHY_RSLT_PRNT
FOREIGN KEY (RESULT_ID)
REFERENCES RESULT (RESULT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;

-- Drop Constraint, Rename and Create Table SQL

ALTER TABLE MEASURE_CONTEXT_ITEM DROP CONSTRAINT FK_MEASURE_CONTEXT_ITEM_GROUP
;
ALTER TABLE MEASURE_CONTEXT_ITEM DROP CONSTRAINT FK_M_CONTEXT_ITEM_ASSAY
;
ALTER TABLE MEASURE_CONTEXT_ITEM DROP CONSTRAINT FK_M_CONTEXT_ITEM_ATTRIBUTE
;
ALTER TABLE MEASURE_CONTEXT_ITEM DROP CONSTRAINT FK_M_CONTEXT_ITEM_M_CONTEXT
;
ALTER TABLE MEASURE_CONTEXT_ITEM DROP CONSTRAINT FK_M_CONTEXT_ITEM_VALUE
;
ALTER TABLE MEASURE_CONTEXT_ITEM DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE MEASURE_CONTEXT_ITEM DROP CONSTRAINT CK_ATTRIBUTE_TYPE
;
ALTER TABLE MEASURE_CONTEXT_ITEM DROP CONSTRAINT CK_MEASURE_CONTEXT_ITEM_QALFR
;
DROP INDEX AK_MEASURE_CONTEXT_ITEM
;
DROP INDEX FK_M_CONTEXT_ITEM_M_CONTEXT
;
DROP INDEX FK_M_CONTEXT_ITEM_ATTRIBUTE
;
DROP INDEX FK_M_CONTEXT_ITEM_VALUE
;
DROP INDEX FK_M_CONTEXT_ITEM_ASSAY
;
DROP INDEX FK_M_CONTEXT_ITEM_QUALIFIER
;
DROP INDEX FK_MEASURE_CONTEXT_ITEM_GROUP
;
ALTER TABLE MEASURE_CONTEXT_ITEM RENAME TO MEASURE_CO_07172012135736000
;
CREATE TABLE MEASURE_CONTEXT_ITEM
(
    MEASURE_CONTEXT_ITEM_ID       NUMBER(19)    NOT NULL,
    GROUP_MEASURE_CONTEXT_ITEM_ID NUMBER(19)        NULL,
    ASSAY_ID                      NUMBER(19)    NOT NULL,
    MEASURE_CONTEXT_ID            NUMBER(19)        NULL,
    ATTRIBUTE_TYPE                VARCHAR2(20)  NOT NULL,
    ATTRIBUTE_ID                  NUMBER(19)    NOT NULL,
    QUALIFIER                     CHAR(2)           NULL,
    VALUE_ID                      NUMBER(19)        NULL,
    EXT_VALUE_ID                  VARCHAR2(60)      NULL,
    VALUE_DISPLAY                 VARCHAR2(500)     NULL,
    VALUE_NUM                     FLOAT(126)        NULL,
    VALUE_MIN                     FLOAT(126)        NULL,
    VALUE_MAX                     FLOAT(126)        NULL,
    VERSION                       NUMBER(38)    DEFAULT 0 NOT NULL,
    DATE_CREATED                  TIMESTAMP(6)  DEFAULT sysdate NOT NULL,
    LAST_UPDATED                  TIMESTAMP(6)      NULL,
    MODIFIED_BY                   VARCHAR2(40)      NULL
)
;
COMMENT ON COLUMN MEASURE_CONTEXT_ITEM.ASSAY_ID IS
'This column is useful for creating the assay defintion before the measures and their contexts have been properly grouped.'
;
COMMENT ON COLUMN MEASURE_CONTEXT_ITEM.VALUE_DISPLAY IS
'This is not a general text entry field, rather it is an easily displayable text version of the other value columns'
;
ALTER TABLE RESULT_CONTEXT_ITEM DROP CONSTRAINT FK_RESULT_CONTEXT_ITEM_GROUP
;
ALTER TABLE RESULT_CONTEXT_ITEM DROP CONSTRAINT FK_RESULT_CONTEXT_ITEM_RESULT
;
ALTER TABLE RESULT_CONTEXT_ITEM DROP CONSTRAINT FK_R_CONTEXT_ITEM_ATTRIBUTE
;
ALTER TABLE RESULT_CONTEXT_ITEM DROP CONSTRAINT FK_R_CONTEXT_ITEM_EXPERIMENT
;
ALTER TABLE RESULT_CONTEXT_ITEM DROP CONSTRAINT FK_R_CONTEXT_ITEM_VALUE
;
ALTER TABLE RESULT_CONTEXT_ITEM DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE RESULT_CONTEXT_ITEM DROP CONSTRAINT CK_RESULT_CONTEXT_ITEM_NULL
;
ALTER TABLE RESULT_CONTEXT_ITEM DROP CONSTRAINT CK_RESULT_CONTEXT_ITEM_QUALFR
;
DROP INDEX FK_R_CONTEXT_ITEM_EXPERIMENT
;
DROP INDEX FK_R_CONTEXT_ITEM_ATTRIBUTE
;
DROP INDEX FK_R_CONTEXT_ITEM_VALUE
;
DROP INDEX FK_R_CONTEXT_ITEM_QUALIFIER
;
DROP INDEX FK_RESULT_CONTEXT_ITEM_RESULT
;
DROP INDEX FK_RESULT_CONTEXT_ITEM_GROUP
;
ALTER TABLE RESULT_CONTEXT_ITEM RENAME TO RESULT_CON_07172012135738000
;
CREATE TABLE RESULT_CONTEXT_ITEM
(
    RESULT_CONTEXT_ITEM_ID  NUMBER(19)    NOT NULL,
    GROUP_RESULT_CONTEXT_ID NUMBER(19)        NULL,
    EXPERIMENT_ID           NUMBER(19)    NOT NULL,
    RESULT_ID               NUMBER(19)        NULL,
    ATTRIBUTE_ID            NUMBER(19)    NOT NULL,
    VALUE_ID                NUMBER(19)        NULL,
    EXT_VALUE_ID            VARCHAR2(60)      NULL,
    QUALIFIER               CHAR(2)           NULL,
    VALUE_NUM               FLOAT(126)        NULL,
    VALUE_MIN               FLOAT(126)        NULL,
    VALUE_MAX               FLOAT(126)        NULL,
    VALUE_DISPLAY           VARCHAR2(500)     NULL,
    VERSION                 NUMBER(38)    DEFAULT 0 NOT NULL,
    DATE_CREATED            TIMESTAMP(6)  DEFAULT sysdate NOT NULL,
    LAST_UPDATED            TIMESTAMP(6)      NULL,
    MODIFIED_BY             VARCHAR2(40)      NULL
)
;
COMMENT ON COLUMN RESULT_CONTEXT_ITEM.VALUE_DISPLAY IS
'This is not a general text entry field, rather it is an easily displayable text version of the other value columns'
;


-- Insert Data SQL

ALTER TABLE MEASURE_CONTEXT_ITEM LOGGING
;
ALTER TABLE RESULT_CONTEXT_ITEM LOGGING
;

-- Add Indexes SQL

CREATE UNIQUE INDEX AK_MEASURE_CONTEXT_ITEM
    ON MEASURE_CONTEXT_ITEM(ASSAY_ID,MEASURE_CONTEXT_ID,GROUP_MEASURE_CONTEXT_ITEM_ID,ATTRIBUTE_ID,ATTRIBUTE_TYPE,VALUE_DISPLAY)
;
CREATE INDEX FK_M_CONTEXT_ITEM_M_CONTEXT
    ON MEASURE_CONTEXT_ITEM(MEASURE_CONTEXT_ID)
;
CREATE INDEX FK_M_CONTEXT_ITEM_ATTRIBUTE
    ON MEASURE_CONTEXT_ITEM(ATTRIBUTE_ID)
;
CREATE INDEX FK_M_CONTEXT_ITEM_VALUE
    ON MEASURE_CONTEXT_ITEM(VALUE_ID)
;
CREATE INDEX FK_M_CONTEXT_ITEM_ASSAY
    ON MEASURE_CONTEXT_ITEM(ASSAY_ID)
;
CREATE INDEX FK_M_CONTEXT_ITEM_QUALIFIER
    ON MEASURE_CONTEXT_ITEM(QUALIFIER)
;
CREATE INDEX FK_MEASURE_CONTEXT_ITEM_GROUP
    ON MEASURE_CONTEXT_ITEM(GROUP_MEASURE_CONTEXT_ITEM_ID)
;
CREATE INDEX FK_R_CONTEXT_ITEM_EXPERIMENT
    ON RESULT_CONTEXT_ITEM(EXPERIMENT_ID)
;
CREATE INDEX FK_R_CONTEXT_ITEM_ATTRIBUTE
    ON RESULT_CONTEXT_ITEM(ATTRIBUTE_ID)
;
CREATE INDEX FK_R_CONTEXT_ITEM_VALUE
    ON RESULT_CONTEXT_ITEM(VALUE_ID)
;
CREATE INDEX FK_R_CONTEXT_ITEM_QUALIFIER
    ON RESULT_CONTEXT_ITEM(QUALIFIER)
;
CREATE INDEX FK_RESULT_CONTEXT_ITEM_RESULT
    ON RESULT_CONTEXT_ITEM(RESULT_ID)
;
CREATE INDEX FK_RESULT_CONTEXT_ITEM_GROUP
    ON RESULT_CONTEXT_ITEM(GROUP_RESULT_CONTEXT_ID)
;

-- Add Constraint SQL

ALTER TABLE MEASURE_CONTEXT_ITEM ADD CONSTRAINT PK_MEASURE_CONTEXT_ITEM
PRIMARY KEY (MEASURE_CONTEXT_ITEM_ID)
;
ALTER TABLE MEASURE_CONTEXT_ITEM ADD CONSTRAINT CK_ATTRIBUTE_TYPE
CHECK (ATTRIBUTE_TYPE in ('Fixed', 'List', 'Range', 'Number'))
;
ALTER TABLE MEASURE_CONTEXT_ITEM ADD CONSTRAINT CK_MEASURE_CONTEXT_ITEM_QALFR
CHECK (QUALIFIER IN ('= ', '< ', '<=', '> ', '>=', '<<', '>>', '~ '))
;
ALTER TABLE RESULT_CONTEXT_ITEM ADD CONSTRAINT PK_RESULT_CONTEXT_ITEM
PRIMARY KEY (RESULT_CONTEXT_ITEM_ID)
;
ALTER TABLE RESULT_CONTEXT_ITEM ADD CONSTRAINT CK_RESULT_CONTEXT_ITEM_QUALFR
CHECK (Qualifier IN ('= ', '< ', '<=', '> ', '>=', '<<', '>>', '~ '))
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE MEASURE_CONTEXT_ITEM ADD CONSTRAINT FK_MEASURE_CONTEXT_ITEM_GROUP
FOREIGN KEY (GROUP_MEASURE_CONTEXT_ITEM_ID)
REFERENCES MEASURE_CONTEXT_ITEM (MEASURE_CONTEXT_ITEM_ID)
ENABLE VALIDATE
;
ALTER TABLE MEASURE_CONTEXT_ITEM ADD CONSTRAINT FK_M_CONTEXT_ITEM_ASSAY
FOREIGN KEY (ASSAY_ID)
REFERENCES ASSAY (ASSAY_ID)
ENABLE VALIDATE
;
ALTER TABLE MEASURE_CONTEXT_ITEM ADD CONSTRAINT FK_M_CONTEXT_ITEM_ATTRIBUTE
FOREIGN KEY (ATTRIBUTE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE MEASURE_CONTEXT_ITEM ADD CONSTRAINT FK_M_CONTEXT_ITEM_M_CONTEXT
FOREIGN KEY (MEASURE_CONTEXT_ID)
REFERENCES MEASURE_CONTEXT (MEASURE_CONTEXT_ID)
ENABLE VALIDATE
;
ALTER TABLE MEASURE_CONTEXT_ITEM ADD CONSTRAINT FK_M_CONTEXT_ITEM_VALUE
FOREIGN KEY (VALUE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE RESULT_CONTEXT_ITEM ADD CONSTRAINT FK_RESULT_CONTEXT_ITEM_GROUP
FOREIGN KEY (GROUP_RESULT_CONTEXT_ID)
REFERENCES RESULT_CONTEXT_ITEM (RESULT_CONTEXT_ITEM_ID)
ENABLE VALIDATE
;
ALTER TABLE RESULT_CONTEXT_ITEM ADD CONSTRAINT FK_RESULT_CONTEXT_ITEM_RESULT
FOREIGN KEY (RESULT_ID)
REFERENCES RESULT (RESULT_ID)
ENABLE VALIDATE
;
ALTER TABLE RESULT_CONTEXT_ITEM ADD CONSTRAINT FK_R_CONTEXT_ITEM_ATTRIBUTE
FOREIGN KEY (ATTRIBUTE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE RESULT_CONTEXT_ITEM ADD CONSTRAINT FK_R_CONTEXT_ITEM_EXPERIMENT
FOREIGN KEY (EXPERIMENT_ID)
REFERENCES EXPERIMENT (EXPERIMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE RESULT_CONTEXT_ITEM ADD CONSTRAINT FK_R_CONTEXT_ITEM_VALUE
FOREIGN KEY (VALUE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;

--
--  clean up temp tables
--
DROP TABLE MEASURE_CO_07172012135736000
;
DROP TABLE RESULT_CON_07172012135738000
;