CREATE SEQUENCE ERROR_LOG_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    MAXVALUE 2147483648
    NOCYCLE
    CACHE 20
    NOORDER
;

CREATE TABLE ERROR_LOG
(
    ERROR_LOG_ID   NUMBER(19)     NOT NULL,
    ERROR_DATE     DATE           DEFAULT sysdate NOT NULL,
    PROCEDURE_NAME VARCHAR2(120)  NOT NULL,
    ERR_NUM        NUMBER(19)     NOT NULL,
    ERR_MSG        VARCHAR2(1000)     NULL,
    ERR_COMMENT    VARCHAR2(4000)     NULL,
    CONSTRAINT PK_ERROR_LOG PRIMARY KEY (ERROR_LOG_ID)
)
;

CREATE TABLE IDENTIFIER_MAPPING
(
    TABLE_NAME    VARCHAR2(31) NOT NULL,
    SOURCE_SCHEMA VARCHAR2(31) NOT NULL,
    SOURCE_ID     NUMBER(19)   NOT NULL,
    TARGET_ID     NUMBER(19)   NOT NULL,
    CONSTRAINT PK_IDENTIFIER_MAPPING
    PRIMARY KEY (TABLE_NAME,SOURCE_SCHEMA,SOURCE_ID,TARGET_ID)
)
;
CREATE TABLE STATEMENT_LOG
(
    TABLE_NAME  VARCHAR2(63)   NOT NULL,
    IDENTIFIER  NUMBER(19)     NOT NULL,
    ACTION_DATE DATE           DEFAULT sysdate NOT NULL,
    ACTION      VARCHAR2(20)   NOT NULL,
    DATA_CLAUSE VARCHAR2(1000)     NULL,
    CONSTRAINT PK_STATEMENT_LOG
    PRIMARY KEY (TABLE_NAME,IDENTIFIER,ACTION_DATE,ACTION)
)
;
