alter table element add REPLACED_BY_ID NUMBER(19,0);

ALTER TABLE ELEMENT ADD CONSTRAINT FK_ELEMENT_REPLACED_BY FOREIGN KEY (REPLACED_BY_ID)
	  REFERENCES ELEMENT (ELEMENT_ID) DEFERRABLE INITIALLY DEFERRED ENABLE;
