
-- Standard Alter Table SQL

ALTER TABLE IDENTIFIER_MAPPING DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE IDENTIFIER_MAPPING ADD CONSTRAINT PK_IDENTIFIER_MAPPING
PRIMARY KEY (SOURCE_ID,TABLE_NAME,SOURCE_SCHEMA)
;

-- Alter Index SQL

CREATE INDEX SI_IDENTIFIER_MAPPING_TARGET
    ON IDENTIFIER_MAPPING(TARGET_ID,TABLE_NAME)
;
