
-- alter sequences

CREATE SEQUENCE PROJECT_CONTEXT_ITEM_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    MAXVALUE 2147483648
    NOCYCLE
    CACHE 20
    NOORDER
;
-- Standard Alter Table SQL

ALTER TABLE EXPERIMENT DROP CONSTRAINT FK_EXPERIMENT_LABORATORY
;
-- COPY the laboratory data before it vanishes!
INSERT INTO RUN_CONTEXT_ITEM
    (RUN_CONTEXT_ITEM_ID,
    GROUP_RUN_CONTEXT_ID,
    EXPERIMENT_ID,
    DISCRIMINATOR,
    ATTRIBUTE_ID,
    VALUE_ID,
    VERSION,
    DATE_CREATED,
    LAST_UPDATED,
    MODIFIED_BY
    )
SELECT
    RUN_CONTEXT_ITEM_ID_SEQ.NEXTVAL,
    RUN_CONTEXT_ITEM_ID_SEQ.CURRVAL GROUP_RUN_CONTEXT_ID,
    EXPERIMENT_ID,
    'Experiment'  DISCRIMINATOR,
    224 ATTRIBUTE_ID,
    LABORATORY_ID VALUE_ID,
    VERSION,
    DATE_CREATED,
    LAST_UPDATED,
    MODIFIED_BY
FROM EXPERIMENT
WHERE LABORATORY_ID IS NOT NULL
;
COMMIT
;
ALTER TABLE EXPERIMENT DROP (LABORATORY_ID)
;
ALTER TABLE IDENTIFIER_MAPPING DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE IDENTIFIER_MAPPING ADD CONSTRAINT PK_IDENTIFIER_MAPPING
PRIMARY KEY (SOURCE_ID,TABLE_NAME,SOURCE_SCHEMA)
;

-- Drop Constraint, Rename and Create Table SQL

ALTER TABLE PROJECT_EXPERIMENT DROP CONSTRAINT FK_PROJECT_EXPRMNT_EXPERIMENT
;
ALTER TABLE PROJECT_EXPERIMENT DROP CONSTRAINT FK_PROJECT_EXPRMNT_FLW_EXPRMNT
;
ALTER TABLE PROJECT_EXPERIMENT DROP CONSTRAINT FK_PROJECT_EXPRMNT_PROJECT
;
ALTER TABLE PROJECT_EXPERIMENT DROP CONSTRAINT FK_PROJECT_EXPRMNT_STAGE
;
ALTER TABLE PROJECT_STEP_ITEM DROP CONSTRAINT FK_PROJECT_STEP_ITEM_EXPRMNT
;
ALTER TABLE PROJECT_EXPERIMENT DROP PRIMARY KEY DROP INDEX
;
DROP INDEX FK_PROJECT_EXPRMNT_PROJECT
;
DROP INDEX FK_PROJECT_EXPRMNT_EXPERIMENT
;
DROP INDEX FK_PROJECT_EXPRMNT_STAGE
;
DROP INDEX FK_PROJECT_EXPRMNT_FLW_EXPRMNT
;
ALTER TABLE PROJECT_EXPERIMENT RENAME TO PROJECT_EX_08212012221026000
;
CREATE TABLE PROJECT_STEP
(
    PROJECT_STEP_ID       NUMBER(19)     NOT NULL,
    PROJECT_ID            NUMBER(19)     NOT NULL,
    EXPERIMENT_ID         NUMBER(19)     NOT NULL,
    FOLLOWS_EXPERIMENT_ID NUMBER(19)         NULL,
    DESCRIPTION           VARCHAR2(1000)     NULL,
    VERSION               NUMBER(38)     DEFAULT 0 NOT NULL,
    DATE_CREATED          TIMESTAMP(6)   DEFAULT sysdate NOT NULL,
    LAST_UPDATED          TIMESTAMP(6)       NULL,
    MODIFIED_BY           VARCHAR2(40)       NULL
)
;
ALTER TABLE PROJECT_STEP_ITEM DROP CONSTRAINT FK_PROJECT_STEP_ELEMENT_ATTR
;
ALTER TABLE PROJECT_STEP_ITEM DROP CONSTRAINT FK_PROJECT_STEP_ELEMENT_VALUE
;
ALTER TABLE PROJECT_STEP_ITEM DROP CONSTRAINT FK_PROJECT_STEP_ITEM_GROUP
;
ALTER TABLE PROJECT_STEP_ITEM DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE PROJECT_STEP_ITEM DROP CONSTRAINT CK_PROJECT_STEP_ITEM_QUALIFIER
;
DROP INDEX FK_PROJECT_STEP_ITEM_EXPRMNT
;
DROP INDEX FK_PROJECT_STEP_ITEM_ATTRIBUTE
;
DROP INDEX FK_PROJECT_STEP_ITEM_VALUE
;
DROP INDEX FK_PROJECT_STEP_ITEM_QUALIFIER
;
DROP INDEX FK_PROJECT_STEP_ITEM_GROUP
;
ALTER TABLE PROJECT_STEP_ITEM RENAME TO PROJECT_ST_08212012221031000
;
CREATE TABLE PROJECT_CONTEXT_ITEM
(
    PROJECT_CONTEXT_ITEM_ID  NUMBER(19)    NOT NULL,
    GROUP_PROJECT_CONTEXT_ID NUMBER(19)        NULL,
    PROJECT_ID               NUMBER(19)        NULL,
    PROJECT_STEP_ID          NUMBER(19)        NULL,
    DISCRIMINATOR            VARCHAR2(20)  DEFAULT 'Project' NOT NULL,
    ATTRIBUTE_ID             NUMBER(19)    NOT NULL,
    VALUE_ID                 NUMBER(19)        NULL,
    EXT_VALUE_ID             VARCHAR2(60)      NULL,
    QUALIFIER                CHAR(2)           NULL,
    VALUE_DISPLAY            VARCHAR2(500)     NULL,
    VALUE_NUM                FLOAT(126)        NULL,
    VALUE_MIN                FLOAT(126)        NULL,
    VALUE_MAX                FLOAT(126)        NULL,
    VERSION                  NUMBER(38)    DEFAULT 0 NOT NULL,
    DATE_CREATED             TIMESTAMP(6)  DEFAULT sysdate NOT NULL,
    LAST_UPDATED             TIMESTAMP(6)      NULL,
    MODIFIED_BY              VARCHAR2(40)      NULL
)
;
COMMENT ON COLUMN PROJECT_CONTEXT_ITEM.VALUE_DISPLAY IS
'This is not a general text entry field, rather it is an easily displayable text version of the other value columns'
;

-- Insert Data SQL

ALTER SESSION ENABLE PARALLEL DML
;
INSERT INTO PROJECT_STEP(
                 PROJECT_STEP_ID,
                 PROJECT_ID,
                 EXPERIMENT_ID,
                 FOLLOWS_EXPERIMENT_ID,
                 DESCRIPTION,
                 VERSION,
                 DATE_CREATED,
                 LAST_UPDATED,
                 MODIFIED_BY
                )
          SELECT
                 PROJECT_EXPERIMENT_ID,
                 PROJECT_ID,
                 EXPERIMENT_ID,
                 FOLLOWS_EXPERIMENT_ID,
                 DESCRIPTION,
                 VERSION,
                 DATE_CREATED,
                 LAST_UPDATED,
                 MODIFIED_BY
            FROM PROJECT_EX_08212012221026000
;
COMMIT
;
ALTER TABLE PROJECT_STEP LOGGING
;
ALTER SESSION ENABLE PARALLEL DML
;
INSERT INTO PROJECT_CONTEXT_ITEM(
                         PROJECT_CONTEXT_ITEM_ID,
                         GROUP_PROJECT_CONTEXT_ID,
                         PROJECT_ID,
                         PROJECT_STEP_ID,
                         DISCRIMINATOR,
                         ATTRIBUTE_ID,
                         VALUE_ID,
                         EXT_VALUE_ID,
                         QUALIFIER,
                         VALUE_DISPLAY,
                         VALUE_NUM,
                         VALUE_MIN,
                         VALUE_MAX,
                         VERSION,
                         DATE_CREATED,
                         LAST_UPDATED,
                         MODIFIED_BY
                        )
                  SELECT
                         PROJECT_STEP_ITEM_ID,
                         GROUP_CONTEXT_iTEM_ID,
                         NULL PROJECT_ID,
                         PROJECT_EXPERIMENT_ID,
                         'Step',    -- cos it only has step data.
                         ATTRIBUTE_ID,
                         VALUE_ID,
                         NULL,
                         QUALIFIER,
                         VALUE_DISPLAY,
                         VALUE_NUM,
                         VALUE_MIN,
                         VALUE_MAX,
                         VERSION,
                         DATE_CREATED,
                         LAST_UPDATED,
                         MODIFIED_BY
                    FROM PROJECT_ST_08212012221031000
;

-- now capture the stage from the previous prroject_experiment
INSERT INTO PROJECT_CONTEXT_ITEM(
                         PROJECT_CONTEXT_ITEM_ID,
                         GROUP_PROJECT_CONTEXT_ID,
                         PROJECT_ID,
                         PROJECT_STEP_ID,
                         DISCRIMINATOR,
                         ATTRIBUTE_ID,
                         VALUE_ID,
                         EXT_VALUE_ID,
                         QUALIFIER,
                         VALUE_DISPLAY,
                         VALUE_NUM,
                         VALUE_MIN,
                         VALUE_MAX,
                         VERSION,
                         DATE_CREATED,
                         LAST_UPDATED,
                         MODIFIED_BY
                        )
                  SELECT
                         PROJECT_CONTEXT_ITEM_ID_SEQ.NEXTVAL,
                         PROJECT_CONTEXT_ITEM_ID_SEQ.CURRVAL  GROUP_PROJECT_CONTEXT_ITEM_ID,
                         NULL PROJECT_ID,
                         PROJECT_EXPERIMENT_ID,
                         'Step',
                         206 STAGE_ID,  -- from Element for 'Assay stage'
                         STAGE_ID VALUE_ID,
                         NULL,
                         NULL QUALIFIER,
                         (SELECT LABEL FROM ELEMENT
                            WHERE ELEMENT_ID = STAGE_ID) VALUE_DISPLAY,
                         NULL VALUE_NUM,
                         NULL VALUE_MIN,
                         NULL VALUE_MAX,
                         VERSION,
                         DATE_CREATED,
                         LAST_UPDATED,
                         MODIFIED_BY
                  FROM PROJECT_EX_08212012221026000
;

COMMIT
;
ALTER TABLE PROJECT_CONTEXT_ITEM LOGGING
;

-- Add Constraint SQL

ALTER TABLE PROJECT_STEP ADD CONSTRAINT PK_PROJECT_STEP
PRIMARY KEY (PROJECT_STEP_ID)
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT PK_PROJECT_STEP_ITEM
PRIMARY KEY (PROJECT_CONTEXT_ITEM_ID)
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT CK_PROJECT_STEP_ITEM_QUALIFIER
CHECK (Qualifier IN ('= ', '< ', '<=', '> ', '>=', '<<', '>>', '~ '))
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT CK_PROJ_CONTEXT_ITEM_DISCRIM
CHECK ((discriminator = 'Project' AND project_id IS NOT NULL AND project_step_id IS NULL)
       OR
      (discriminator = 'Step' AND project_id IS NULL AND project_step_id IS NOT NULL))
;

-- Alter Index SQL
CREATE INDEX FK_PROJECT_STEP_PROJECT
    ON PROJECT_STEP(PROJECT_ID)
;
CREATE INDEX FK_PROJECT_STEP_EXPERIMENT
    ON PROJECT_STEP(EXPERIMENT_ID)
;
CREATE INDEX FK_PROJECT_STEP_FLLWS_EXPRMNT
    ON PROJECT_STEP(FOLLOWS_EXPERIMENT_ID)
;
CREATE INDEX FK_PROJECT_STEP_ITEM_EXPRMNT
    ON PROJECT_CONTEXT_ITEM(PROJECT_STEP_ID)
;
CREATE INDEX FK_PROJECT_STEP_ITEM_ATTRIBUTE
    ON PROJECT_CONTEXT_ITEM(ATTRIBUTE_ID)
;
CREATE INDEX FK_PROJECT_STEP_ITEM_VALUE
    ON PROJECT_CONTEXT_ITEM(VALUE_ID)
;
CREATE INDEX FK_PROJECT_STEP_ITEM_QUALIFIER
    ON PROJECT_CONTEXT_ITEM(QUALIFIER)
;
CREATE INDEX FK_PROJECT_STEP_ITEM_GROUP
    ON PROJECT_CONTEXT_ITEM(GROUP_PROJECT_CONTEXT_ID)
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE PROJECT_STEP ADD CONSTRAINT FK_PROJECT_STEP_EXPERIMENT
FOREIGN KEY (EXPERIMENT_ID)
REFERENCES EXPERIMENT (EXPERIMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_STEP ADD CONSTRAINT FK_PROJECT_STEP_FLLWS_EXPRMNT
FOREIGN KEY (FOLLOWS_EXPERIMENT_ID)
REFERENCES EXPERIMENT (EXPERIMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_STEP ADD CONSTRAINT FK_PROJECT_STEP_PROJECT
FOREIGN KEY (PROJECT_ID)
REFERENCES PROJECT (PROJECT_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT FK_PROJ_CONTEXT_ITEM_STEP
FOREIGN KEY (PROJECT_STEP_ID)
REFERENCES PROJECT_STEP (PROJECT_STEP_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT FK_PROJ_CONTEXT_ITEM_PROJECT
FOREIGN KEY (PROJECT_ID)
REFERENCES PROJECT (PROJECT_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT FK_PROJ_CONTEXT_ITEM_ATTR
FOREIGN KEY (ATTRIBUTE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT FK_PROJ_CONTEXT_ITEM_VALUE
FOREIGN KEY (VALUE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT FK_PROJ_CONTEXT_ITEM_GROUP
FOREIGN KEY (GROUP_PROJECT_CONTEXT_ID)
REFERENCES PROJECT_CONTEXT_ITEM (PROJECT_CONTEXT_ITEM_ID)
ENABLE VALIDATE
;
