INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (0, null, 0, 'STAGE', 'Singular root to ensure tree viewers work');
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (1, 0, 224, 'confirmatory assay', 'An assay performed to confirm activity of perturbagens identified in a primary assay; may be performed as replicate measurements or as a concentration-response assay.');
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (2, 0, 225, 'lead-optimization assay', 'An assay performed in the lead-optimization stage on a relatively small number of active perturbagens; typically a high-quality concentration-response assay.');
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (3, 0, 226, 'primary assay', 'An assay performed (usually first in a campaign) to identify potentially biologically active pertubagens; usually performed at a single concentration with one or two measurements.');
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (4, 0, 227, 'secondary assay', 'An assay performed following a confirmatory assay to confirm the biological activity a perturbagen using a different assay type or design; may address mode-of-action, toxicity, activity profile, and selectivity.');
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (5, 4, 228, 'alternate confirmatory assay', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (6, 5, 231, 'alternate assay components', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (7, 5, 232, 'alternate assay format', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (8, 5, 233, 'alternate assay type', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (9, 5, 234, 'orthogonal assay design', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (10, 5, 235, 'orthogonal assay detection method', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (11, 5, 280, 'alternate assay parameters', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (12, 4, 229, 'counter-screening assay', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (13, 12, 236, 'alternate target assay', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (14, 12, 237, 'compound toxicity assay', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (15, 12, 238, 'parental cell line assay', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (16, 12, 239, 'physiochemical assay', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (17, 12, 240, 'construct variant assay', null);
INSERT INTO stage(NODE_ID, PARENT_NODE_ID, STAGE_ID, STAGE, DESCRIPTION) VALUES (18, 4, 230, 'selectivity assay', null);
