/* Copyright (c) 2014, The Broad Institute
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of The Broad Institute nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL The Broad Institute BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */

package db

/**
 * @author Muhammad.Rafique
 * Date Created: 13/02/07
 * Date Updated: 13/10/09
 */
class AssayQueries {
	final static String ASSAY_SUMMARY_BYID = "SELECT A.ASSAY_ID ADID, A.ASSAY_STATUS Status, A.ASSAY_NAME Name, A.ASSAY_SHORT_NAME ShortName, A.DESIGNED_BY DesignedBy, to_char(A.DATE_CREATED, 'MM/DD/YYYY') as DateCreated, A.ASSAY_TYPE DefinitionType, A.ASSAY_VERSION Version, to_char(A.LAST_UPDATED, 'MM/DD/YYYY') as LastUpdated, A.MODIFIED_BY ModifiedBy FROM ASSAY A WHERE A.ASSAY_ID = ?";
	final static String ASSAY_SEARCH_COUNT = "SELECT COUNT(A.ASSAY_NAME) AssayCount FROM ASSAY A WHERE LOWER(A.ASSAY_NAME) LIKE ?";
	final static String ASSAY_SEARCH_RSULTS = "SELECT A.ASSAY_ID AID FROM ASSAY A WHERE LOWER(A.ASSAY_NAME) LIKE ?";
	final static String ASSAY_CONTEXTS = "SELECT AC.CONTEXT_NAME ContextName FROM ASSAY_CONTEXT AC WHERE AC.ASSAY_ID = ? AND AC.CONTEXT_TYPE = ?";
	final static String ASSAY_CONTEXT_ITEMS = "SELECT E.LABEL AttributeLabel, ACI.VALUE_DISPLAY ValueDisplay FROM ASSAY_CONTEXT_ITEM ACI, ELEMENT E WHERE ACI.ATTRIBUTE_ID = E.ELEMENT_ID AND ACI.ASSAY_CONTEXT_ID IN(SELECT AC.ASSAY_CONTEXT_ID ContextID FROM ASSAY_CONTEXT AC WHERE AC.ASSAY_ID = ? AND AC.CONTEXT_TYPE = ? AND AC.CONTEXT_NAME = ?)";	
	final static String ASSAY_DOCUMENT = "SELECT DOCUMENT_NAME as Name, DOCUMENT_CONTENT as Content FROM ASSAY_DOCUMENT WHERE ASSAY_ID = ? AND LOWER(DOCUMENT_TYPE) = ?";
	final static String ASSAY_SUMMARY_CREATED = "SELECT ASSAY_ID as ADID, ASSAY_NAME as Name, ASSAY_TYPE as DefinitionType, ASSAY_STATUS as Status, DISPLAY_NAME as Owner FROM (SELECT * FROM ASSAY A INNER JOIN ROLE R on A.OWNER_ROLE_ID = R.ROLE_ID WHERE A.ASSAY_NAME = ? ORDER BY A.ASSAY_ID DESC, A.DATE_CREATED) WHERE ROWNUM = 1";
	String ASSAY_MEASURES_LIST = "SELECT R.RESULT_TYPE_NAME measure, S.LABEL label FROM MEASURE M INNER JOIN RESULT_TYPE_TREE R ON R.RESULT_TYPE_ID = M.RESULT_TYPE_ID LEFT JOIN STATS_MODIFIER_TREE S ON S.ELEMENT_ID = M.STATS_MODIFIER_ID WHERE M.ASSAY_ID = ?";
	String ASSAY_ASSOCIATED_MEASURE_CONTEXT = "SELECT R.RESULT_TYPE_NAME measure, AC.CONTEXT_NAME context FROM ASSAY_CONTEXT_MEASURE ACM INNER JOIN MEASURE M ON M.MEASURE_ID = ACM.MEASURE_ID INNER JOIN RESULT_TYPE_TREE R ON R.RESULT_TYPE_ID = M.RESULT_TYPE_ID INNER JOIN ASSAY_CONTEXT AC ON AC.ASSAY_CONTEXT_ID = ACM.ASSAY_CONTEXT_ID WHERE AC.ASSAY_ID = ? AND R.RESULT_TYPE_NAME = ?";
}
