insert into element (element_id, label, description, element_status) values (495, 'gastric juice', '', 'Published');
insert into element (element_id, label, description, element_status) values (496, 'gene', '', 'Published');
insert into element (element_id, label, description, element_status) values (497, 'GO:molecular function (EXTERNAL ONTOLOGY)', '', 'Published');
insert into element (element_id, label, description, element_status) values (498, 'grams-per-liter', '', 'Published');
insert into element (element_id, label, description, element_status) values (499, 'graphical calculation endpoint', 'An endpoint derived from calculus-based analysis of graphical measures.', 'Published');
insert into element (element_id, label, description, element_status) values (500, 'hair', '', 'Published');
insert into element (element_id, label, description, element_status) values (501, 'heart', '', 'Published');
insert into element (element_id, label, description, element_status) values (502, 'hyper-flask', '', 'Published');
insert into element (element_id, label, description, element_status) values (503, 'hypothalamus', '', 'Published');
insert into element (element_id, label, description, element_status) values (505, 'image-based', '', 'Published');
insert into element (element_id, label, description, element_status) values (506, 'immune tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (507, 'individual', '', 'Published');
insert into element (element_id, label, description, element_status) values (508, 'integumentary tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (509, 'intended activator', '', 'Published');
insert into element (element_id, label, description, element_status) values (510, 'intended inhibitor', '', 'Published');
insert into element (element_id, label, description, element_status) values (511, 'intended modulator', '', 'Published');
insert into element (element_id, label, description, element_status) values (512, 'intestine', '', 'Published');
insert into element (element_id, label, description, element_status) values (513, 'Kd', '', 'Published');
insert into element (element_id, label, description, element_status) values (514, 'Ki', '', 'Published');
insert into element (element_id, label, description, element_status) values (515, 'kidney', '', 'Published');
insert into element (element_id, label, description, element_status) values (516, 'Km', 'A Michaelis-Menten binding constant.', 'Published');
insert into element (element_id, label, description, element_status) values (517, 'larynx', '', 'Published');
insert into element (element_id, label, description, element_status) values (519, 'ligament', '', 'Published');
insert into element (element_id, label, description, element_status) values (520, 'liver', '', 'Published');
insert into element (element_id, label, description, element_status) values (521, 'logD', '', 'Published');
insert into element (element_id, label, description, element_status) values (522, 'logP', '', 'Published');
insert into element (element_id, label, description, element_status) values (523, 'loss-of-signal', 'A trend in which the desired signal for perturbagens of interest is a decrease in the raw assay measurement.', 'Published');
insert into element (element_id, label, description, element_status) values (524, 'lung', '', 'Published');
insert into element (element_id, label, description, element_status) values (525, 'lymph node', '', 'Published');
insert into element (element_id, label, description, element_status) values (526, 'macromolecule', '', 'Published');
insert into element (element_id, label, description, element_status) values (527, 'macromolecule description', 'A long name for a gene or protein from a trusted international source (e.g., Entrez, UniProt).', 'Published');
insert into element (element_id, label, description, element_status) values (528, 'macromolecule identifier', 'An external database unique identifier, such as an accession number, for a gene or protein from a trusted international source (e.g., Entrez, UniProt).', 'Published');
insert into element (element_id, label, description, element_status) values (529, 'macromolecule identifier source', 'A trusted international source (e.g., Entrez, UniProt) of the gene or protein name.', 'Published');
insert into element (element_id, label, description, element_status) values (571, 'perilymph', '', 'Published');
insert into element (element_id, label, description, element_status) values (530, 'macromolecule name', 'A short symbol or name for a gene or protein from a trusted international source (e.g., Entrez, UniProt).', 'Published');
insert into element (element_id, label, description, element_status) values (531, 'macromolecule type', '', 'Published');
insert into element (element_id, label, description, element_status) values (532, 'mammary gland', '', 'Published');
insert into element (element_id, label, description, element_status) values (130, 'cell modification', 'This describes the type of alterations performed on the cell line, which include plasmid transfection, viral transduction, cell fusion, etc.', 'Published');
insert into element (element_id, label, description, element_status) values (136, 'protein form', '', 'Published');
insert into element (element_id, label, description, element_status) values (137, 'protein preparation method', '', 'Published');
insert into element (element_id, label, description, element_status) values (138, 'protein purity', '', 'Published');
insert into element (element_id, label, description, element_status) values (157, 'protein sequence', '', 'Published');
insert into element (element_id, label, description, element_status) values (281, 'DNA construct', '', 'Published');
insert into element (element_id, label, description, element_status) values (64, 'assay readout name', '', 'Published');
insert into element (element_id, label, description, element_status) values (122, 'signal direction', 'It is the trend of measured readout signal, whether it increases or decreases in perturbagen treated wells, as compared to the untreated or carrier-treated wells in an assay.', 'Published');
insert into element (element_id, label, description, element_status) values (123, 'unit of measurement', 'It is the inite magnitude of a physical quantity or of time. It has a quantity and a unit associated with it.', 'Published');
insert into element (element_id, label, description, element_status) values (124, 'wavelength', 'For fluorescence measurements, it is the wavelength at which the fluorophore is excited and the wavelength at which it emits fluorescence. In the case of absorbance, it is the wavelength at which light is absorbed by a biological entity or a dye.', 'Published');
insert into element (element_id, label, description, element_status) values (117, 'incubation time', 'An interval of time between the addition of pertubagen, substrate, or cell modification, and the measurement of change using the detection method of the assay.', 'Published');
insert into element (element_id, label, description, element_status) values (533, 'measured profile', '', 'Published');
insert into element (element_id, label, description, element_status) values (119, 'temperature', '', 'Published');
insert into element (element_id, label, description, element_status) values (120, 'pH', '', 'Published');
insert into element (element_id, label, description, element_status) values (330, 'endpoint assay', 'In this assay, change in activity is measured at one time point.', 'Published');
insert into element (element_id, label, description, element_status) values (331, 'kinetic assay', 'In this assay, change in activity is measured at several time points over a period of time.', 'Published');
insert into element (element_id, label, description, element_status) values (270, 'RNA construct type', '', 'Published');
insert into element (element_id, label, description, element_status) values (534, 'measured value', '', 'Published');
insert into element (element_id, label, description, element_status) values (272, 'RNA construct source', '', 'Published');
insert into element (element_id, label, description, element_status) values (273, 'RNA construct sequence', '', 'Published');
insert into element (element_id, label, description, element_status) values (535, 'measurement throughput', 'A description of the throughput qualities of measurements performed on each sample (i.e., perturbagen) in the instance; includes instance-specific information not intrinsic to the assay, such as number of replicates and number of sample concentrations tested.', 'Published');
insert into element (element_id, label, description, element_status) values (536, 'measurement type', 'A description of whether a change in an assay is measured once at a fixed end-point, or over a period of time at several time points.', 'Published');
insert into element (element_id, label, description, element_status) values (221, 'small-molecule structure', '', 'Published');
insert into element (element_id, label, description, element_status) values (231, 'alternate assay component', '', 'Published');
insert into element (element_id, label, description, element_status) values (232, 'alternate assay format', '', 'Published');
insert into element (element_id, label, description, element_status) values (233, 'alternate assay type', '', 'Published');
insert into element (element_id, label, description, element_status) values (234, 'orthogonal assay design', '', 'Published');
insert into element (element_id, label, description, element_status) values (235, 'orthogonal assay detection method', '', 'Published');
insert into element (element_id, label, description, element_status) values (280, 'alternate assay parameter', '', 'Published');
insert into element (element_id, label, description, element_status) values (236, 'alternate target assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (237, 'compound toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (238, 'parental cell line assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (239, 'physicochemical assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (240, 'construct variant assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (59, 'staining method', '', 'Published');
insert into element (element_id, label, description, element_status) values (135, 'fixation method', '', 'Published');
insert into element (element_id, label, description, element_status) values (537, 'metabolite-production method', '', 'Published');
insert into element (element_id, label, description, element_status) values (132, 'passage number', '', 'Published');
insert into element (element_id, label, description, element_status) values (538, 'MIC', '', 'Published');
insert into element (element_id, label, description, element_status) values (325, 'growth mode', 'This describes the growth mode of a cell line, whether it grows attached to the culture dish (adherent) or floating (suspension) in the culture medium or partially attached (mixed adherent and suspension).', 'Published');
insert into element (element_id, label, description, element_status) values (134, 'transfection method', '', 'Published');
insert into element (element_id, label, description, element_status) values (139, 'infection method', '', 'Published');
insert into element (element_id, label, description, element_status) values (60, 'construct sequence', '', 'Published');
insert into element (element_id, label, description, element_status) values (282, 'construct gene form', 'It describes whether the gene that is inserted in the construct is wild type or mutated, truncated, etc.', 'Published');
insert into element (element_id, label, description, element_status) values (303, 'construct selectable marker', '', 'Published');
insert into element (element_id, label, description, element_status) values (539, 'microarray', '', 'Published');
insert into element (element_id, label, description, element_status) values (540, 'microtiter plate', '', 'Published');
insert into element (element_id, label, description, element_status) values (541, 'mixed', '', 'Published');
insert into element (element_id, label, description, element_status) values (275, 'shRNA', '', 'Published');
insert into element (element_id, label, description, element_status) values (276, 'siRNA', '', 'Published');
insert into element (element_id, label, description, element_status) values (542, 'mixed phase', '', 'Published');
insert into element (element_id, label, description, element_status) values (543, 'mixed source', '', 'Published');
insert into element (element_id, label, description, element_status) values (328, 'culture serum', 'Cultured cells require serum or growth factors for growth by cell division. Each cell type is grown in a medium supplemented with a variable concentration of serum (up to 20%) which is optimized for its growth. Specialized sera include dextran charcoal treated serum, which lacks certain hormones, growth factors, etc, dialyzed serum, which lacks low molecular weight molecules (below 10,000 MW), such as glucose, amino acids, low molecular weight hormones, cytokines, etc. These sera are used in certain assays to avoid interference from the normal serum components. Most commonly, fetal bovine serum is used in cell culture, but other sera such as horse serum are also used.', 'Published');
insert into element (element_id, label, description, element_status) values (329, 'culture medium', 'The liquid broth used to grow cells, which is optimized for each cell type and includes additives such as growth factors, buffers, amino acids, antibiotics, etc. This information can be obtained from ATCC or found in relevant publications.', 'Published');
insert into element (element_id, label, description, element_status) values (347, 'peptide', '', 'Published');
insert into element (element_id, label, description, element_status) values (348, 'Rhok2', '', 'Published');
insert into element (element_id, label, description, element_status) values (349, 'S6', '', 'Published');
insert into element (element_id, label, description, element_status) values (350, 'Measured Entity', '', 'Published');
insert into element (element_id, label, description, element_status) values (351, 'readout', '', 'Published');
insert into element (element_id, label, description, element_status) values (352, 'nucleotide', '', 'Published');
insert into element (element_id, label, description, element_status) values (353, 'ATP', '', 'Published');
insert into element (element_id, label, description, element_status) values (354, 'HEPES_50mM_7.3pH/MgCl_10mM/BSA_0.1%/DTT_2mM', '', 'Published');
insert into element (element_id, label, description, element_status) values (355, 'Vehicle Components', '', 'Published');
insert into element (element_id, label, description, element_status) values (356, 'HEPES', '', 'Published');
insert into element (element_id, label, description, element_status) values (357, 'MgCl', '', 'Published');
insert into element (element_id, label, description, element_status) values (358, 'BSA', '', 'Published');
insert into element (element_id, label, description, element_status) values (359, 'DTT', '', 'Published');
insert into element (element_id, label, description, element_status) values (360, 'assay mode', '', 'Published');
insert into element (element_id, label, description, element_status) values (361, 'in vitro', '', 'Published');
insert into element (element_id, label, description, element_status) values (544, 'moles-per-liter', '', 'Published');
insert into element (element_id, label, description, element_status) values (545, 'monochrometer-based method', '', 'Published');
insert into element (element_id, label, description, element_status) values (546, 'mucus', '', 'Published');
insert into element (element_id, label, description, element_status) values (547, 'multi-feature extraction', '', 'Published');
insert into element (element_id, label, description, element_status) values (548, 'multi-parameter', '', 'Published');
insert into element (element_id, label, description, element_status) values (549, 'multiple concentration', '', 'Published');
insert into element (element_id, label, description, element_status) values (550, 'multiple repetition', '', 'Published');
insert into element (element_id, label, description, element_status) values (551, 'muscle', '', 'Published');
insert into element (element_id, label, description, element_status) values (552, 'muscular tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (553, 'nail', '', 'Published');
insert into element (element_id, label, description, element_status) values (554, 'natural product', '', 'Published');
insert into element (element_id, label, description, element_status) values (555, 'nerve', '', 'Published');
insert into element (element_id, label, description, element_status) values (556, 'nervous tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (557, 'number', '', 'Published');
insert into element (element_id, label, description, element_status) values (558, 'number-per-liter', '', 'Published');
insert into element (element_id, label, description, element_status) values (559, 'number-per-well', '', 'Published');
insert into element (element_id, label, description, element_status) values (560, 'optical density', 'A concentration of suspensions as measured by the optical density, usually at 600 nM (typically used for cultures of microorganisms).', 'Published');
insert into element (element_id, label, description, element_status) values (561, 'ovary', '', 'Published');
insert into element (element_id, label, description, element_status) values (562, 'pancreas', '', 'Published');
insert into element (element_id, label, description, element_status) values (563, 'parameter number', '', 'Published');
insert into element (element_id, label, description, element_status) values (564, 'parathyroid', '', 'Published');
insert into element (element_id, label, description, element_status) values (572, 'peritoneal fluid', '', 'Published');
insert into element (element_id, label, description, element_status) values (36, 'organism', '', 'Published');
insert into element (element_id, label, description, element_status) values (38, 'protein', '', 'Published');
insert into element (element_id, label, description, element_status) values (39, 'tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (267, 'cultured cell', '', 'Published');
insert into element (element_id, label, description, element_status) values (26, 'small molecule', '', 'Published');
insert into element (element_id, label, description, element_status) values (0, 'Root', 'single root to ensure tree viewers like this', 'Published');
insert into element (element_id, label, description, element_status) values (1, 'BARD ASSAY ONTOLOGY', '', 'Published');
insert into element (element_id, label, description, element_status) values (5, 'assay', 'An experiment carried out to test the effect of a perturbagen on a biological entity, measuring one or more readout facilitated by an assay design and assay type, and record the results one or more endpoint that quantifies or qualifies the extent of perturbation.', 'Published');
insert into element (element_id, label, description, element_status) values (9, 'assay component', '', 'Published');
insert into element (element_id, label, description, element_status) values (21, 'assay kit', '', 'Published');
insert into element (element_id, label, description, element_status) values (22, 'assay reagent', '', 'Published');
insert into element (element_id, label, description, element_status) values (23, 'biological entity', 'A material entity of biological origin (e.g., protein, cell culture, tissue).', 'Published');
insert into element (element_id, label, description, element_status) values (32, 'biological fluid', '', 'Published');
insert into element (element_id, label, description, element_status) values (10, 'assay component role', 'A role associated with an assay component.', 'Published');
insert into element (element_id, label, description, element_status) values (27, 'control role', '', 'Published');
insert into element (element_id, label, description, element_status) values (40, 'negative control', '', 'Published');
insert into element (element_id, label, description, element_status) values (41, 'positive control', '', 'Published');
insert into element (element_id, label, description, element_status) values (333, 'high-signal control', '', 'Published');
insert into element (element_id, label, description, element_status) values (334, 'low-signal control', '', 'Published');
insert into element (element_id, label, description, element_status) values (335, 'background control', '', 'Published');
insert into element (element_id, label, description, element_status) values (28, 'detector role', '', 'Published');
insert into element (element_id, label, description, element_status) values (42, 'analyte', '', 'Published');
insert into element (element_id, label, description, element_status) values (43, 'dye', '', 'Published');
insert into element (element_id, label, description, element_status) values (44, 'measured component', '', 'Published');
insert into element (element_id, label, description, element_status) values (45, 'radioisotope label', '', 'Published');
insert into element (element_id, label, description, element_status) values (48, 'tracer', '', 'Published');
insert into element (element_id, label, description, element_status) values (29, 'receiver role', '', 'Published');
insert into element (element_id, label, description, element_status) values (46, 'receptor', '', 'Published');
insert into element (element_id, label, description, element_status) values (69, 'target', '', 'Published');
insert into element (element_id, label, description, element_status) values (30, 'modulator role', '', 'Published');
insert into element (element_id, label, description, element_status) values (49, 'cytokine', '', 'Published');
insert into element (element_id, label, description, element_status) values (50, 'attractant', '', 'Published');
insert into element (element_id, label, description, element_status) values (51, 'differentiation agent', '', 'Published');
insert into element (element_id, label, description, element_status) values (53, 'growth factor', '', 'Published');
insert into element (element_id, label, description, element_status) values (57, 'sensitizer', '', 'Published');
insert into element (element_id, label, description, element_status) values (62, 'blocker', '', 'Published');
insert into element (element_id, label, description, element_status) values (63, 'inducer', '', 'Published');
insert into element (element_id, label, description, element_status) values (65, 'ligand', '', 'Published');
insert into element (element_id, label, description, element_status) values (66, 'modulator', '', 'Published');
insert into element (element_id, label, description, element_status) values (67, 'mutagen', '', 'Published');
insert into element (element_id, label, description, element_status) values (283, 'agonist', '', 'Published');
insert into element (element_id, label, description, element_status) values (308, 'antagonist', '', 'Published');
insert into element (element_id, label, description, element_status) values (319, 'activator', '', 'Published');
insert into element (element_id, label, description, element_status) values (322, 'reference', '', 'Published');
insert into element (element_id, label, description, element_status) values (31, 'reagent role', '', 'Published');
insert into element (element_id, label, description, element_status) values (47, 'substrate', '', 'Published');
insert into element (element_id, label, description, element_status) values (52, 'solvent', '', 'Published');
insert into element (element_id, label, description, element_status) values (54, 'growth medium', '', 'Published');
insert into element (element_id, label, description, element_status) values (55, 'media component', '', 'Published');
insert into element (element_id, label, description, element_status) values (58, 'transfection agent', '', 'Published');
insert into element (element_id, label, description, element_status) values (70, 'buffer', '', 'Published');
insert into element (element_id, label, description, element_status) values (71, 'carrier', '', 'Published');
insert into element (element_id, label, description, element_status) values (72, 'charge carrier', '', 'Published');
insert into element (element_id, label, description, element_status) values (73, 'co-enzyme', '', 'Published');
insert into element (element_id, label, description, element_status) values (74, 'co-factor', '', 'Published');
insert into element (element_id, label, description, element_status) values (75, 'co-substrate', '', 'Published');
insert into element (element_id, label, description, element_status) values (76, 'coupled enzyme', '', 'Published');
insert into element (element_id, label, description, element_status) values (77, 'cross-linker', '', 'Published');
insert into element (element_id, label, description, element_status) values (78, 'de-polarizer', '', 'Published');
insert into element (element_id, label, description, element_status) values (79, 'detergent', '', 'Published');
insert into element (element_id, label, description, element_status) values (80, 'fixative', '', 'Published');
insert into element (element_id, label, description, element_status) values (81, 'ionophore', '', 'Published');
insert into element (element_id, label, description, element_status) values (82, 'reducing agent', '', 'Published');
insert into element (element_id, label, description, element_status) values (83, 'solute', '', 'Published');
insert into element (element_id, label, description, element_status) values (84, 'vehicle', '', 'Published');
insert into element (element_id, label, description, element_status) values (11, 'assay design', '', 'Published');
insert into element (element_id, label, description, element_status) values (85, 'assay format', 'A concept of an assay based on the biological or chemical features of the assay components, including biochemical assays with purified protein, cell-based assays performed whole cells, and organism-based assays performed in an organism.', 'Published');
insert into element (element_id, label, description, element_status) values (89, 'biochemical format', 'An in vitro format used to measure the activity of a biological macromolecule, either purified protein or nucleic acid; most often a homogenous assay format, but can be heterogeneous if a solid phase (e.g. beads) is used to immobilize the macromolecule.', 'Published');
insert into element (element_id, label, description, element_status) values (90, 'cell-based format', 'A heterogenous assay format that involves living cells of eukaryotic origin.', 'Published');
insert into element (element_id, label, description, element_status) values (91, 'cell-free format', 'An in vitro format where biological material originates from cells, but does not use live cells nor purified macromolecules; most often a homogenous assay format, but can be heterogeneous if a solid phase (e.g. beads) is used to immobilize the components.', 'Published');
insert into element (element_id, label, description, element_status) values (92, 'organism-based format', 'A heterogenous assay format that involves living organisms.', 'Published');
insert into element (element_id, label, description, element_status) values (93, 'tissue-based format', 'A heterogenous assay format that involves tissue derived from a living organism.', 'Published');
insert into element (element_id, label, description, element_status) values (86, 'assay parameter', '', 'Published');
insert into element (element_id, label, description, element_status) values (88, 'detection method type', 'A physical method (technology) used to measure one or more readout of the effect caused by a perturbagen in the assay.', 'Published');
insert into element (element_id, label, description, element_status) values (98, 'fluorescence method', '', 'Published');
insert into element (element_id, label, description, element_status) values (99, 'imaging method', '', 'Published');
insert into element (element_id, label, description, element_status) values (100, 'label-free method', '', 'Published');
insert into element (element_id, label, description, element_status) values (101, 'luminescence method', '', 'Published');
insert into element (element_id, label, description, element_status) values (102, 'radiometry method', '', 'Published');
insert into element (element_id, label, description, element_status) values (103, 'spectrophotometry method', '', 'Published');
insert into element (element_id, label, description, element_status) values (104, 'assay method', 'The underlying method (technology) and assay strategy used to determine the action of the perturbagen in the assay system.', 'Published');
insert into element (element_id, label, description, element_status) values (336, 'functional method', '', 'Published');
insert into element (element_id, label, description, element_status) values (337, 'physical method', '', 'Published');
insert into element (element_id, label, description, element_status) values (12, 'assay measurement', 'An abstract concept to group multiple assay readouts and allow description of an assay that measures more than one effect of a perturbagen on the biological entity.', 'Published');
insert into element (element_id, label, description, element_status) values (126, 'assay readout ID', '', 'Published');
insert into element (element_id, label, description, element_status) values (13, 'assay type', '', 'Published');
insert into element (element_id, label, description, element_status) values (144, 'molecular interaction assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (161, 'protein-DNA interaction assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (162, 'protein-RNA interaction assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (163, 'protein-protein interaction assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (164, 'protein-small molecule interaction assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (145, 'binding assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (146, 'cell morphology assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (147, 'cell motility assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (148, 'toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (180, 'acute toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (181, 'carcinogenicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (182, 'cell-proliferation assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (183, 'clinical pathology assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (184, 'cytotoxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (185, 'dermal toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (186, 'developmental toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (187, 'endocrine disruption assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (188, 'genotoxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (189, 'immune-response assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (190, 'inhalation toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (191, 'neurotoxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (192, 'ocular toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (193, 'oxidative stress assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (194, 'phototoxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (195, 'repeat-dose toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (196, 'reproductive toxicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (149, 'enzyme activity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (150, 'gene-expression assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (151, 'membrane potential assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (152, 'physico-chemical property determination assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (172, 'acid-ionization constant determination assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (173, 'identification assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (174, 'lipophilicity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (175, 'melting-point determination assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (176, 'purity determination assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (177, 'solubility assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (178, 'stability assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (207, 'concentration determination assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (153, 'protein-folding assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (154, 'protein turnover assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (155, 'RNA splicing assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (156, 're-distribution assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (158, 'signal transduction assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (165, 'cytokine secretion assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (166, 'post-translational modification assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (167, 'reporter-gene assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (168, 'second messenger assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (159, 'transporter assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (160, 'viability assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (179, 'ion-channel assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (197, 'safety pharmacology assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (198, 'drug abuse assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (199, 'drug-interaction assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (200, 'QT interval assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (201, 'organism assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (202, 'behavioral assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (203, 'metastasis assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (204, 'pharmacodynamic assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (205, 'pharmacokinetic assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (206, 'therapeutic efficacy assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (208, 'cell communication assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (209, 'cell cycle assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (210, 'cell growth assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (211, 'cellular metabolic process assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (212, 'coagulation assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (213, 'development assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (214, 'multi-organism process assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (215, 'system process assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (252, 'curve-fit specification', 'A descripition of curve-fit parameters used to obtain an endpoint by fitting a single function across a range of measurements; contains information about curve-fit parameters, methods, properties (e.g., Hill coefficient), concentration range, and replicates.', 'Published');
insert into element (element_id, label, description, element_status) values (253, 'normalization method', 'A description of a data normalization method (e.g., normalized percent distribution, Z-score, B-score) used to correct raw data for inference errors (i.e., false negatives and false positives), especially after testing at a single concentration or with a small number of replicates.', 'Published');
insert into element (element_id, label, description, element_status) values (254, 'endpoint mode-of-action', 'A description of the qualitative effect of a perturbagen in an assay (e.g., inhibition, activation, cytotoxicity).', 'Published');
insert into element (element_id, label, description, element_status) values (2, 'BARD DICTIONARY', '', 'Published');
insert into element (element_id, label, description, element_status) values (387, '0.5-uL tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (388, '1.5-uL tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (306, 'primary cell name', '', 'Published');
insert into element (element_id, label, description, element_status) values (307, 'detection instrument', '', 'Published');
insert into element (element_id, label, description, element_status) values (309, 'fluorescence-activated cell-sorter', '', 'Published');
insert into element (element_id, label, description, element_status) values (310, 'microscope', '', 'Published');
insert into element (element_id, label, description, element_status) values (105, 'MDS IX Micro', '', 'Published');
insert into element (element_id, label, description, element_status) values (106, 'MDS IX Ultra', '', 'Published');
insert into element (element_id, label, description, element_status) values (107, 'Perkin Elmer Operetta', '', 'Published');
insert into element (element_id, label, description, element_status) values (311, 'plate-reader', '', 'Published');
insert into element (element_id, label, description, element_status) values (313, 'Perkin Elmer Enspire', '', 'Published');
insert into element (element_id, label, description, element_status) values (314, 'Perkin Elmer Envision', '', 'Published');
insert into element (element_id, label, description, element_status) values (315, 'Perkin Elmer Viewlux', '', 'Published');
insert into element (element_id, label, description, element_status) values (316, 'Thermo Fisher VarioSkan', '', 'Published');
insert into element (element_id, label, description, element_status) values (312, 'plate-scanner', '', 'Published');
insert into element (element_id, label, description, element_status) values (317, 'TTP Labtech Acumen', '', 'Published');
insert into element (element_id, label, description, element_status) values (3, 'EXTERNAL (MULTI-USE) DICTIONARY', '', 'Published');
insert into element (element_id, label, description, element_status) values (389, '1536-well plate', '', 'Published');
insert into element (element_id, label, description, element_status) values (390, '15-mL conical tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (391, '2.0-uL tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (392, '24-well plate', '', 'Published');
insert into element (element_id, label, description, element_status) values (393, '250-mL conical tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (394, '3456-well plate', '', 'Published');
insert into element (element_id, label, description, element_status) values (395, '384-well plate', '', 'Published');
insert into element (element_id, label, description, element_status) values (396, '48-well plate', '', 'Published');
insert into element (element_id, label, description, element_status) values (397, '50-mL conical tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (346, 'coupled substrate', '', 'Published');
insert into element (element_id, label, description, element_status) values (4, 'EXTERNAL ONTOLOGY', '', 'Published');
insert into element (element_id, label, description, element_status) values (287, 'GO:biological process (EXTERNAL ONTOLOGY)', '', 'Published');
insert into element (element_id, label, description, element_status) values (289, 'DO:disease (HUMAN DISEASE)', '', 'Published');
insert into element (element_id, label, description, element_status) values (398, '6-well plate', '', 'Published');
insert into element (element_id, label, description, element_status) values (399, '96-well plate', '', 'Published');
insert into element (element_id, label, description, element_status) values (400, 'academic chemist', '', 'Published');
insert into element (element_id, label, description, element_status) values (94, 'nucleic-acid format', 'A format in which the perturbagen targets nucleic acid (DNA or RNA) to regulate its function.', 'Published');
insert into element (element_id, label, description, element_status) values (95, 'protein format', 'A format in which the perturbagen targets a protein to regulate its function.', 'Published');
insert into element (element_id, label, description, element_status) values (96, 'sub-cellular format', 'A format using sub-cellular organelles (but not individually purified proteins) obtained by cell lysis and fractionation (e.g., differential centrifugation).', 'Published');
insert into element (element_id, label, description, element_status) values (97, 'whole-cell lysate format', 'A format using cells whose membranes have been ruptured (e.g., mechanically, osmotically) and whose lysate is used without separation techniques.', 'Published');
insert into element (element_id, label, description, element_status) values (401, 'activity threshold', '', 'Published');
insert into element (element_id, label, description, element_status) values (402, 'adenoid', '', 'Published');
insert into element (element_id, label, description, element_status) values (403, 'adherent', '', 'Published');
insert into element (element_id, label, description, element_status) values (61, 'assay readout', '', 'Published');
insert into element (element_id, label, description, element_status) values (111, 'assay biosafety level', 'A biosafety level is the level of biocontainment required to isolate hazardous biological agents in an enclosed facility. The levels of containment range from the lowest biosafety level of 1 to the highest at level 4.', 'Published');
insert into element (element_id, label, description, element_status) values (112, 'assay condition', 'A set of optimization guidelines used to minimize the time and cost of assay implementation, while providing reliable assay performance.', 'Published');
insert into element (element_id, label, description, element_status) values (113, 'assay footprint', 'This describes the physical format such as plate density in which an assay is performed, which is generally a microplate format, but can also be an array format.', 'Published');
insert into element (element_id, label, description, element_status) values (404, 'adrenal gland', '', 'Published');
insert into element (element_id, label, description, element_status) values (405, 'amniotic fluid', '', 'Published');
insert into element (element_id, label, description, element_status) values (116, 'assay readout content', 'This describes the throughput and information content generated. Categorizing multiplexed (i.e. multiple targets measured simultaneously) and multiparametric assays and high content (image-based) and regular (plate reader) assays.', 'Published');
insert into element (element_id, label, description, element_status) values (406, 'aqueous humor', '', 'Published');
insert into element (element_id, label, description, element_status) values (332, 'assay phase', 'It refers to whether all the assay components are in solution or some are in solid phase, which determines their ability to scatter light.', 'Published');
insert into element (element_id, label, description, element_status) values (338, 'amplification method', '', 'Published');
insert into element (element_id, label, description, element_status) values (339, 'radiation-based method', '', 'Published');
insert into element (element_id, label, description, element_status) values (169, 'phosphorylation assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (170, 'methylation assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (171, 'acetylation assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (268, 'RNA construct collection name', '', 'Published');
insert into element (element_id, label, description, element_status) values (269, 'RNA construct perturbagen', '', 'Published');
insert into element (element_id, label, description, element_status) values (140, 'small-molecule perturbagen', '', 'Published');
insert into element (element_id, label, description, element_status) values (222, 'small-molecule collection name', '', 'Published');
insert into element (element_id, label, description, element_status) values (277, 'small-molecule collection source', 'A description of whether a small-molecule collection was purchased from a vendor or generated in an academic institution.', 'Published');
insert into element (element_id, label, description, element_status) values (228, 'alternate confirmatory assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (229, 'counter-screening assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (230, 'selectivity assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (407, 'area-under-curve', 'Area (e.g., integral) under a curve.', 'Published');
insert into element (element_id, label, description, element_status) values (343, 'Bmax', 'It is the amount of drug required to saturate a population of receptors and a measure of the number of receptors present in the sample. It is derived from Scatchard plot of binding data. It is analogous to Vmax in enzyme kinetics. The units of Bmax include cpm, sites/cell or fmol/mg. http', 'Published');
insert into element (element_id, label, description, element_status) values (344, 'Vmax', 'Vmax is ined as the maximum initial velocity of an enzyme catalyzed reaction under the given conditions, and it is measured in units of quantity of substrate transformed per unit time for a given concentration of enzyme.', 'Published');
insert into element (element_id, label, description, element_status) values (408, 'assay component concentration', '', 'Published');
insert into element (element_id, label, description, element_status) values (409, 'assay component type', '', 'Published');
insert into element (element_id, label, description, element_status) values (410, 'assay detection method', '', 'Published');
insert into element (element_id, label, description, element_status) values (411, 'assay humidity', '', 'Published');
insert into element (element_id, label, description, element_status) values (412, 'assay incubation time', 'An interval of time between the addition of pertubagen, substrate, or cell modification, and the measurement of change using the detection method of the assay.', 'Published');
insert into element (element_id, label, description, element_status) values (413, 'assay panel ID', 'Assay panel IDs of assay panels (within a project) included in a screening campaign.', 'Published');
insert into element (element_id, label, description, element_status) values (414, 'assay percent carbon dioxide', '', 'Published');
insert into element (element_id, label, description, element_status) values (415, 'assay percent oxygen', '', 'Published');
insert into element (element_id, label, description, element_status) values (416, 'assay pH', '', 'Published');
insert into element (element_id, label, description, element_status) values (417, 'assay pressure', '', 'Published');
insert into element (element_id, label, description, element_status) values (418, 'assay readout type', '', 'Published');
insert into element (element_id, label, description, element_status) values (419, 'assay temperature', '', 'Published');
insert into element (element_id, label, description, element_status) values (420, 'auto-fluorescence method', '', 'Published');
insert into element (element_id, label, description, element_status) values (421, 'bi-directional', 'A trend in which the desired signal for perturbagens of interest can be either an increase or a decrease in the raw assay measurement.', 'Published');
insert into element (element_id, label, description, element_status) values (422, 'bile', '', 'Published');
insert into element (element_id, label, description, element_status) values (423, 'biological fluid type', '', 'Published');
insert into element (element_id, label, description, element_status) values (424, 'BL1', '', 'Published');
insert into element (element_id, label, description, element_status) values (425, 'BL2', '', 'Published');
insert into element (element_id, label, description, element_status) values (426, 'BL2+', '', 'Published');
insert into element (element_id, label, description, element_status) values (427, 'BL3', '', 'Published');
insert into element (element_id, label, description, element_status) values (428, 'BL4', '', 'Published');
insert into element (element_id, label, description, element_status) values (429, 'bladder', '', 'Published');
insert into element (element_id, label, description, element_status) values (362, 'in vivo', '', 'Published');
insert into element (element_id, label, description, element_status) values (363, 'in silico', '', 'Published');
insert into element (element_id, label, description, element_status) values (365, 'Kinase Glo', '', 'Published');
insert into element (element_id, label, description, element_status) values (366, 'concentration', '', 'Published');
insert into element (element_id, label, description, element_status) values (367, 'incubation temperature', '', 'Published');
insert into element (element_id, label, description, element_status) values (368, 'software', '', 'Published');
insert into element (element_id, label, description, element_status) values (369, 'Number of exclusions', '', 'Published');
insert into element (element_id, label, description, element_status) values (370, 'Number of points', '', 'Published');
insert into element (element_id, label, description, element_status) values (372, 'Assay Explorer', '', 'Published');
insert into element (element_id, label, description, element_status) values (374, 'log IC50', '', 'Published');
insert into element (element_id, label, description, element_status) values (375, 'Hill coeff', '', 'Published');
insert into element (element_id, label, description, element_status) values (376, 'hill s0', '', 'Published');
insert into element (element_id, label, description, element_status) values (377, 'hill sinf', '', 'Published');
insert into element (element_id, label, description, element_status) values (378, 'hill ds', '', 'Published');
insert into element (element_id, label, description, element_status) values (379, 'Statistical', '', 'Published');
insert into element (element_id, label, description, element_status) values (380, 'Count', '', 'Published');
insert into element (element_id, label, description, element_status) values (381, 'Chi Squared', '', 'Published');
insert into element (element_id, label, description, element_status) values (382, 'R Squared', '', 'Published');
insert into element (element_id, label, description, element_status) values (383, '%', '', 'Published');
insert into element (element_id, label, description, element_status) values (384, 'deg C', '', 'Published');
insert into element (element_id, label, description, element_status) values (385, 's', '', 'Published');
insert into element (element_id, label, description, element_status) values (386, 'uM', '', 'Published');
insert into element (element_id, label, description, element_status) values (430, 'blood', '', 'Published');
insert into element (element_id, label, description, element_status) values (431, 'blood vessel', '', 'Published');
insert into element (element_id, label, description, element_status) values (432, 'bone', '', 'Published');
insert into element (element_id, label, description, element_status) values (433, 'brain', '', 'Published');
insert into element (element_id, label, description, element_status) values (434, 'breast milk', '', 'Published');
insert into element (element_id, label, description, element_status) values (435, 'bronchus', '', 'Published');
insert into element (element_id, label, description, element_status) values (436, 'calculated value', 'A readout in which the reported value is actually derived from raw values but in which the calculated value is typically reported by the instrument or is immediately used (e.g., temperature shift in a protein melting assay, ratio of luminescence values in a DualGlo assay, or a fluorescence polarization or anisotropy assay).', 'Published');
insert into element (element_id, label, description, element_status) values (437, 'cartilage', '', 'Published');
insert into element (element_id, label, description, element_status) values (439, 'cell-culture component', 'Components of a specific medium in which a cell culture is prepared, which is optimized for its growth; includes medium additives such as serum, growth factors, buffers, amino acids, and antibiotics (this information may be obtained from ATCC or found in relevant publications).', 'Published');
insert into element (element_id, label, description, element_status) values (440, 'cell-culture condition', '', 'Published');
insert into element (element_id, label, description, element_status) values (441, 'cell-fusion method', '', 'Published');
insert into element (element_id, label, description, element_status) values (442, 'cell-processing method', '', 'Published');
insert into element (element_id, label, description, element_status) values (443, 'cell-proliferation method', '', 'Published');
insert into element (element_id, label, description, element_status) values (444, 'cerebrospinal fluid', '', 'Published');
insert into element (element_id, label, description, element_status) values (445, 'cerumen', '', 'Published');
insert into element (element_id, label, description, element_status) values (446, 'circulatory tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (447, 'Cmax', 'A maximal concentration achieved in a dosing experiment (maximum point of a concentration curve).', 'Published');
insert into element (element_id, label, description, element_status) values (448, 'colon', '', 'Published');
insert into element (element_id, label, description, element_status) values (449, 'commercial vendor', '', 'Published');
insert into element (element_id, label, description, element_status) values (450, 'concentration throughput', '', 'Published');
insert into element (element_id, label, description, element_status) values (451, 'concentration unit', '', 'Published');
insert into element (element_id, label, description, element_status) values (452, 'concentration value', '', 'Published');
insert into element (element_id, label, description, element_status) values (453, 'concentration-point number', '', 'Published');
insert into element (element_id, label, description, element_status) values (454, 'conical tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (455, 'construct regulatory region', 'A name of a promoter or artificial regulatory element inserted upstream of a reporter gene in a DNA construct.', 'Published');
insert into element (element_id, label, description, element_status) values (456, 'construct vector name', 'A name for a vector, an extrachromosomal, self-replicating DNA molecule that is used as a vehicle to deliver a DNA construct into cells, e.g., plasmid vector (pGEM-T, pBluescript), lentiviral vector, retroviral vector.', 'Published');
insert into element (element_id, label, description, element_status) values (457, 'cps', 'Counts per second', 'Published');
insert into element (element_id, label, description, element_status) values (458, 'culture additive', '', 'Published');
insert into element (element_id, label, description, element_status) values (459, 'culture antibiotic', '', 'Published');
insert into element (element_id, label, description, element_status) values (460, 'cultured cell name', '', 'Published');
insert into element (element_id, label, description, element_status) values (461, 'degradation method', '', 'Published');
insert into element (element_id, label, description, element_status) values (462, 'detection method filter', '', 'Published');
insert into element (element_id, label, description, element_status) values (463, 'diaphragm', '', 'Published');
insert into element (element_id, label, description, element_status) values (464, 'difference', '', 'Published');
insert into element (element_id, label, description, element_status) values (465, 'digestive tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (466, 'DNA microarray', '', 'Published');
insert into element (element_id, label, description, element_status) values (468, 'electrophysiology method', '', 'Published');
insert into element (element_id, label, description, element_status) values (469, 'emission', '', 'Published');
insert into element (element_id, label, description, element_status) values (470, 'emission filter', '', 'Published');
insert into element (element_id, label, description, element_status) values (471, 'endocrine tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (472, 'endolymph', '', 'Published');
insert into element (element_id, label, description, element_status) values (473, 'engineered gene form', '', 'Published');
insert into element (element_id, label, description, element_status) values (474, 'engineered genotype name', '', 'Published');
insert into element (element_id, label, description, element_status) values (475, 'engineered organism', '', 'Published');
insert into element (element_id, label, description, element_status) values (476, 'engineered regulatory region', '', 'Published');
insert into element (element_id, label, description, element_status) values (477, 'engineered selectable marker', '', 'Published');
insert into element (element_id, label, description, element_status) values (478, 'engineered sequence', '', 'Published');
insert into element (element_id, label, description, element_status) values (479, 'Eppendorf tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (480, 'esophagus', '', 'Published');
insert into element (element_id, label, description, element_status) values (481, 'excitation', '', 'Published');
insert into element (element_id, label, description, element_status) values (482, 'excitation filter', '', 'Published');
insert into element (element_id, label, description, element_status) values (483, 'excretory tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (484, 'extract', '', 'Published');
insert into element (element_id, label, description, element_status) values (485, 'extract fraction', '', 'Published');
insert into element (element_id, label, description, element_status) values (486, 'fallopian tube', '', 'Published');
insert into element (element_id, label, description, element_status) values (487, 'feature number', '', 'Published');
insert into element (element_id, label, description, element_status) values (488, 'filter-based method', '', 'Published');
insert into element (element_id, label, description, element_status) values (489, 'fluorescence anisotropy', '', 'Published');
insert into element (element_id, label, description, element_status) values (490, 'fluorescence polarization', '', 'Published');
insert into element (element_id, label, description, element_status) values (491, 'fold change', '', 'Published');
insert into element (element_id, label, description, element_status) values (492, 'frequency', 'A unit of measure for observations based on a number of events counted, including collection of photons by an instrument as in fluorescence or luminescence assays.', 'Published');
insert into element (element_id, label, description, element_status) values (493, 'gain-of-signal', 'A trend in which the desired signal for perturbagens of interest is an increase in the raw assay measurement.', 'Published');
insert into element (element_id, label, description, element_status) values (494, 'gall bladder', '', 'Published');
insert into element (element_id, label, description, element_status) values (670, 'AC10', 'The concentration at which the fitted curve passes activity threshold 10.', 'Published');
insert into element (element_id, label, description, element_status) values (671, 'AC1000', 'The concentration at which the fitted curve passes activity threshold 1000.', 'Published');
insert into element (element_id, label, description, element_status) values (672, 'AC35', 'The concentration at which the fitted curve passes activity threshold 35.', 'Published');
insert into element (element_id, label, description, element_status) values (673, 'AC40', 'The concentration at which the fitted curve passes activity threshold 40.', 'Published');
insert into element (element_id, label, description, element_status) values (675, 'AC500', 'The concentration at which the fitted curve passes activity threshold 500.', 'Published');
insert into element (element_id, label, description, element_status) values (676, 'AUC', 'Area under the curve', 'Published');
insert into element (element_id, label, description, element_status) values (678, 'EC20', 'The concentration at which the fitted curve passes efficacy threshold 20%', 'Published');
insert into element (element_id, label, description, element_status) values (679, 'EC30', 'The concentration at which the fitted curve passes efficacy threshold 30%', 'Published');
insert into element (element_id, label, description, element_status) values (681, 'EC80', 'The concentration at which the fitted curve passes efficacy threshold 80%', 'Published');
insert into element (element_id, label, description, element_status) values (682, 'EC90', 'The concentration at which the fitted curve passes efficacy threshold 90%', 'Published');
insert into element (element_id, label, description, element_status) values (683, 'FOC', 'Fold of 620 nm signal over DMSO control at 6.25 uM; average of triplicate measurement.', 'Published');
insert into element (element_id, label, description, element_status) values (685, 'IC80', 'Concentration of 80% Inhibition', 'Published');
insert into element (element_id, label, description, element_status) values (688, 'Km/Vmax', 'The slope of the Lineweaver-Burke plot, defined as the ratio Km/Vmax, at the indicated inhibitor test concentration', 'Published');
insert into element (element_id, label, description, element_status) values (690, 'activation voltage', 'half activation voltage', 'Published');
insert into element (element_id, label, description, element_status) values (695, 'confidence limit - 95%', '95% confidence interval boundaries', 'Published');
insert into element (element_id, label, description, element_status) values (696, 'cytotoxicity', 'proportion cells that died', 'Published');
insert into element (element_id, label, description, element_status) values (697, 'deactivation time', 'deactivation time constant', 'Published');
insert into element (element_id, label, description, element_status) values (698, 'fold activation', 'The maximal fold activation is observed at the lowest concentration.', 'Published');
insert into element (element_id, label, description, element_status) values (699, 'fold selectivity', 'The ratio of the test compound concentration at which less than 50% inhibition of the anti-target is observed over the test compound concentration at which greater than or equal to 50% inhibition', 'Published');
insert into element (element_id, label, description, element_status) values (706, 'log CC50', 'Log10 of the qualified CC50 from the cytotoxicity assay', 'Published');
insert into element (element_id, label, description, element_status) values (707, 'log EC50', 'base 10 logarithm of EC50 value', 'Published');
insert into element (element_id, label, description, element_status) values (709, 'log MIC', 'Log10 of the qualified MIC from the inhibitor assay', 'Published');
insert into element (element_id, label, description, element_status) values (710, 'log virus titer change', 'Virus titer change observed in log scale', 'Published');
insert into element (element_id, label, description, element_status) values (711, 'luminescence', 'luminescence signal', 'Published');
insert into element (element_id, label, description, element_status) values (712, 'melting point', 'Melting temperature of the substance under test', 'Published');
insert into element (element_id, label, description, element_status) values (713, 'peak current', 'peak current normalized by peak current in the absence of compound', 'Published');
insert into element (element_id, label, description, element_status) values (716, 'percent augmentation', '%Augmentation', 'Published');
insert into element (element_id, label, description, element_status) values (718, 'percent count', 'The percentage count of cells exceeding', 'Published');
insert into element (element_id, label, description, element_status) values (719, 'percent current', '% current remaining', 'Published');
insert into element (element_id, label, description, element_status) values (720, 'percent displacement', '% displacement', 'Published');
insert into element (element_id, label, description, element_status) values (721, 'percent efficacy', '% Efficacy in primary screening', 'Published');
insert into element (element_id, label, description, element_status) values (722, 'percent efflux', 'Percentage of Efflux', 'Published');
insert into element (element_id, label, description, element_status) values (723, 'percent emax bottom', 'Average percentage of maximum effect in kinetic time window', 'Published');
insert into element (element_id, label, description, element_status) values (724, 'percent emax top', 'Average percentage of maximum effect in kinetic time window', 'Published');
insert into element (element_id, label, description, element_status) values (726, 'percent of control', 'percent of control - activity or inhibition', 'Published');
insert into element (element_id, label, description, element_status) values (727, 'percent survival', '% cell survival', 'Published');
insert into element (element_id, label, description, element_status) values (728, 'percent toxicity', '% toxicity = 1-(cell density in sample well / average cell density of all MIN controls on the plate)*100', 'Published');
insert into element (element_id, label, description, element_status) values (729, 'percent viability', '0', 'Published');
insert into element (element_id, label, description, element_status) values (730, 'pubchem score', 'arbitrary score assigned to an experimental result by PubChem users - Not to be used for new assays', 'Published');
insert into element (element_id, label, description, element_status) values (732, 'selectivity index', 'Ration of IC50 in one assay to IC50 in another assay', 'Published');
insert into element (element_id, label, description, element_status) values (736, 'z-prime', 'the Zprime value of the population calculated as 1-(3*(PosSD + NegSD)/ ABS(PosAvg -NegAvg))  (ref Wikipedia)', 'Published');
insert into element (element_id, label, description, element_status) values (737, 'z-score', 'Z-score for the normal distribution (ref Wikipedia)', 'Published');
insert into element (element_id, label, description, element_status) values (738, 'zone diameter', 'Size of the growth inhibition zone for a disc loaded with test compounds ', 'Published');
insert into element (element_id, label, description, element_status) values (6, 'biology', 'A biological entity or process that is the presumed subject of the assay; may refer to a macromolecule whose activity is being regulated, or to a cell-biological process (e.g., neurite outgrowth).', 'Published');
insert into element (element_id, label, description, element_status) values (14, 'molecular target', 'A biological entity that has the role of target of an assay; usually a biological macromolecule that interacts with a perturbagen to produce the readout detected by the assay.', 'Published');
insert into element (element_id, label, description, element_status) values (7, 'project management', '', 'Published');
insert into element (element_id, label, description, element_status) values (18, 'assay instance', '', 'Published');
insert into element (element_id, label, description, element_status) values (24, 'perturbagen collection', '', 'Published');
insert into element (element_id, label, description, element_status) values (25, 'RNA construct collection', '', 'Published');
insert into element (element_id, label, description, element_status) values (141, 'perturbagen delivery', 'A description of whether perturbagens are tested individually or as pooled mixtures.', 'Published');
insert into element (element_id, label, description, element_status) values (142, 'small-molecule collection', '', 'Published');
insert into element (element_id, label, description, element_status) values (219, 'assay ID', '', 'Published');
insert into element (element_id, label, description, element_status) values (223, 'assay stage', 'A description of the purpose of an assay within a project; relates to the order of assays in a screening campaign (e.g., a primary assay is performed first to identify hits, which are then confirmed in a confirmatory assay, after which secondary assays further prioritize confirmed hits).', 'Published');
insert into element (element_id, label, description, element_status) values (224, 'confirmatory assay', 'An assay performed to confirm activity of perturbagens identified in a primary assay; may be performed as replicate measurements or as a concentration-response assay.', 'Published');
insert into element (element_id, label, description, element_status) values (225, 'lead-optimization assay', 'An assay performed in the lead-optimization stage on a relatively small number of active perturbagens; typically a high-quality concentration-response assay.', 'Published');
insert into element (element_id, label, description, element_status) values (226, 'primary assay', 'An assay performed (usually first in a campaign) to identify potentially biologically active pertubagens; usually performed at a single concentration with one or two measurements.', 'Published');
insert into element (element_id, label, description, element_status) values (227, 'secondary assay', 'An assay performed following a confirmatory assay to confirm the biological activity a perturbagen using a different assay type or design; may address mode-of-action, toxicity, activity profile, and selectivity.', 'Published');
insert into element (element_id, label, description, element_status) values (19, 'depositor information', '', 'Published');
insert into element (element_id, label, description, element_status) values (241, 'depositor laboratory', '', 'Published');
insert into element (element_id, label, description, element_status) values (242, 'deposition date', '', 'Published');
insert into element (element_id, label, description, element_status) values (20, 'project information', '', 'Published');
insert into element (element_id, label, description, element_status) values (243, 'biological project goal', '', 'Published');
insert into element (element_id, label, description, element_status) values (247, 'intended mode-of-action', '', 'Published');
insert into element (element_id, label, description, element_status) values (248, 'intended molecular target', '', 'Published');
insert into element (element_id, label, description, element_status) values (244, 'screening campaign', 'A concept to group multiple assay instances whose sequential performance is used to identify active pertubagens with a specific function and establish mode-of-action; usally progresses through primary assay, confirmatory assays, secondary assays, and lead-optimization assays.', 'Published');
insert into element (element_id, label, description, element_status) values (245, 'screening campaign name', '', 'Published');
insert into element (element_id, label, description, element_status) values (246, 'assay instance ID', '', 'Published');
insert into element (element_id, label, description, element_status) values (274, 'project name', '', 'Published');
insert into element (element_id, label, description, element_status) values (216, 'assay panel', 'An abstract concept to group multiple assay instances and allow description of a group of assays that measure more than one effect of a perturbagen directed at prioritization by viewing the results together (e.g., a selectivity panel of assays for activity against each member of a family of related proteins).', 'Published');
insert into element (element_id, label, description, element_status) values (218, 'assay panel name', '', 'Published');
insert into element (element_id, label, description, element_status) values (8, 'result', '', 'Published');
insert into element (element_id, label, description, element_status) values (255, 'concentration endpoint', 'An endpoint expressed as a concentration at which a perturbagen mediates a ined response (e.g., IC50, EC50); always has one value in units of molar concentration.', 'Published');
insert into element (element_id, label, description, element_status) values (256, 'biochemical constant endpoint', 'An endpoint used to express binding constants or enzyme kinetic constants reflecting interactions between ligands and macromolecules (e.g., Bmax, Kd).', 'Published');
insert into element (element_id, label, description, element_status) values (259, 'binding constant', 'This endpoint type describes the bonding affinity between two molecules at equilibrium, e.g., drug-receptor interaction.', 'Published');
insert into element (element_id, label, description, element_status) values (260, 'enzyme kinetic constant', 'Describe kinetics of enzyme-catalyzed reactions. It includes the enzyme kinetic constants namely, Km and Vmax, which help to model the time course of disappearance of substrate and the production of product.', 'Published');
insert into element (element_id, label, description, element_status) values (257, 'response endpoint', 'An endpoint reporting the magnitude or relative magnitude of effect induced by a perturbagen; often expressed relative to control measurements.', 'Published');
insert into element (element_id, label, description, element_status) values (258, 'temperature endpoint', 'An endpoint that reports a change in temperature as a measure of the extent of perturbation (e.g., Tm).', 'Published');
insert into element (element_id, label, description, element_status) values (261, 'profile endpoint', '', 'Published');
insert into element (element_id, label, description, element_status) values (262, 'gene-expression profile', '', 'Published');
insert into element (element_id, label, description, element_status) values (263, 'panel-assay profile', '', 'Published');
insert into element (element_id, label, description, element_status) values (264, 'computational profile', '', 'Published');
insert into element (element_id, label, description, element_status) values (251, 'result detail', '', 'Published');
insert into element (element_id, label, description, element_status) values (655, 'AC50', '', 'Published');
insert into element (element_id, label, description, element_status) values (656, 'Hill Slope', '', 'Published');
insert into element (element_id, label, description, element_status) values (657, 'S0', '', 'Published');
insert into element (element_id, label, description, element_status) values (658, 'Sinf', '', 'Published');
insert into element (element_id, label, description, element_status) values (659, 'logAC50', '', 'Published');
insert into element (element_id, label, description, element_status) values (660, 'Plasmodium falciparum', '', 'Published');
insert into element (element_id, label, description, element_status) values (661, 'environment', '', 'Published');
insert into element (element_id, label, description, element_status) values (662, 'low oxygen', '', 'Published');
insert into element (element_id, label, description, element_status) values (663, 'excitation wavelength', '', 'Published');
insert into element (element_id, label, description, element_status) values (664, 'measurement wavelength', '', 'Published');
insert into element (element_id, label, description, element_status) values (665, 'Marquardt-Levenberg', '', 'Published');
insert into element (element_id, label, description, element_status) values (666, 'RPMI/Albumax_4.16mg/mL', '', 'Published');
insert into element (element_id, label, description, element_status) values (652, 'mg/kg', 'millgrams per kilo - dose measure', 'Published');
insert into element (element_id, label, description, element_status) values (653, 'dose', 'dose measure', 'Published');
insert into element (element_id, label, description, element_status) values (573, 'permeability A-B', '', 'Published');
insert into element (element_id, label, description, element_status) values (574, 'permeability B-A', '', 'Published');
insert into element (element_id, label, description, element_status) values (575, 'pharynx', '', 'Published');
insert into element (element_id, label, description, element_status) values (576, 'photo-uncaging method', '', 'Published');
insert into element (element_id, label, description, element_status) values (577, 'physical property endpoint', 'A measurement of an intrinsic property of a molecular entity.', 'Published');
insert into element (element_id, label, description, element_status) values (578, 'pineal gland', '', 'Published');
insert into element (element_id, label, description, element_status) values (579, 'pituitary gland', '', 'Published');
insert into element (element_id, label, description, element_status) values (580, 'pKa', '', 'Published');
insert into element (element_id, label, description, element_status) values (581, 'pleural fluid', '', 'Published');
insert into element (element_id, label, description, element_status) values (582, 'pooled mixture', '', 'Published');
insert into element (element_id, label, description, element_status) values (583, 'prostate', '', 'Published');
insert into element (element_id, label, description, element_status) values (585, 'PubChem CID', 'A compound identifier of a ined chemical structure, assigned by PubChem.', 'Published');
insert into element (element_id, label, description, element_status) values (586, 'quality assessment', 'A description of commonly used statistical parameters to monitor assay quality, including Z and Z-prime factors; prior to starting a large screen, and after assay optimization and miniaturization, a pilot screen is typically performed to assess quality of an assay using these parameters.', 'Published');
insert into element (element_id, label, description, element_status) values (587, 'ratio', '', 'Published');
insert into element (element_id, label, description, element_status) values (588, 'reaction vessel', '', 'Published');
insert into element (element_id, label, description, element_status) values (589, 'repetition throughput', '', 'Published');
insert into element (element_id, label, description, element_status) values (590, 'repetition-point number', '', 'Published');
insert into element (element_id, label, description, element_status) values (591, 'reproductive tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (592, 'resonance-energy method', '', 'Published');
insert into element (element_id, label, description, element_status) values (593, 'respiratory tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (594, 'result endpoint', '', 'Published');
insert into element (element_id, label, description, element_status) values (595, 'result source', 'Assay instance IDs and assay readout IDs of assay instances and their assay readouts from which a result is derived.', 'Published');
insert into element (element_id, label, description, element_status) values (596, 'RFU', 'Relative fluorescence units, a standard raw measurement for fluorescence-based assays, either direct fluorescence intensity (FI) measurements or energy transfer assays such as FRET.', 'Published');
insert into element (element_id, label, description, element_status) values (597, 'RLU', 'Relative light units, a standard measurement unit for luminescence assays.', 'Published');
insert into element (element_id, label, description, element_status) values (598, 'saliva', '', 'Published');
insert into element (element_id, label, description, element_status) values (599, 'salivary gland', '', 'Published');
insert into element (element_id, label, description, element_status) values (600, 'sebum', '', 'Published');
insert into element (element_id, label, description, element_status) values (601, 'semen', '', 'Published');
insert into element (element_id, label, description, element_status) values (602, 'serum', '', 'Published');
insert into element (element_id, label, description, element_status) values (603, 'single concentration', '', 'Published');
insert into element (element_id, label, description, element_status) values (604, 'single parameter', '', 'Published');
insert into element (element_id, label, description, element_status) values (605, 'single repetition', '', 'Published');
insert into element (element_id, label, description, element_status) values (606, 'single-feature extraction', '', 'Published');
insert into element (element_id, label, description, element_status) values (607, 'skeletal tissue', '', 'Published');
insert into element (element_id, label, description, element_status) values (608, 'skin', '', 'Published');
insert into element (element_id, label, description, element_status) values (609, 'slope', '', 'Published');
insert into element (element_id, label, description, element_status) values (610, 'small-molecule format', 'An assay format with no biological component that is intended to measure the physical properties of a compound and not its effect on a biological system.', 'Published');
insert into element (element_id, label, description, element_status) values (611, 'small-molecule microarray', '', 'Published');
insert into element (element_id, label, description, element_status) values (612, 'solid phase', '', 'Published');
insert into element (element_id, label, description, element_status) values (613, 'solubility', '', 'Published');
insert into element (element_id, label, description, element_status) values (614, 'solution phase', '', 'Published');
insert into element (element_id, label, description, element_status) values (615, 'species (BINOMIAL NOMENCLATURE)', '', 'Published');
insert into element (element_id, label, description, element_status) values (616, 'spinal cord', '', 'Published');
insert into element (element_id, label, description, element_status) values (617, 'spleen', '', 'Published');
insert into element (element_id, label, description, element_status) values (618, 'stomach', '', 'Published');
insert into element (element_id, label, description, element_status) values (619, 'substrate-conversion method', '', 'Published');
insert into element (element_id, label, description, element_status) values (620, 'sum', '', 'Published');
insert into element (element_id, label, description, element_status) values (621, 'summary assay', '', 'Published');
insert into element (element_id, label, description, element_status) values (622, 'suspension', '', 'Published');
insert into element (element_id, label, description, element_status) values (623, 'sweat', '', 'Published');
insert into element (element_id, label, description, element_status) values (625, 'T-175', '', 'Published');
insert into element (element_id, label, description, element_status) values (626, 'T-225', '', 'Published');
insert into element (element_id, label, description, element_status) values (627, 'T-25', '', 'Published');
insert into element (element_id, label, description, element_status) values (628, 'T-75', '', 'Published');
insert into element (element_id, label, description, element_status) values (629, 'tears', '', 'Published');
insert into element (element_id, label, description, element_status) values (630, 'tendon', '', 'Published');
insert into element (element_id, label, description, element_status) values (631, 'testis', '', 'Published');
insert into element (element_id, label, description, element_status) values (632, 'thymus', '', 'Published');
insert into element (element_id, label, description, element_status) values (633, 'thyroid', '', 'Published');
insert into element (element_id, label, description, element_status) values (634, 'time', '', 'Published');
insert into element (element_id, label, description, element_status) values (635, 'time endpoint', '', 'Published');
insert into element (element_id, label, description, element_status) values (636, 'time-course', '', 'Published');
insert into element (element_id, label, description, element_status) values (637, 'tissue type', '', 'Published');
insert into element (element_id, label, description, element_status) values (638, 'tissue-culture flask', '', 'Published');
insert into element (element_id, label, description, element_status) values (639, 'tonsil', '', 'Published');
insert into element (element_id, label, description, element_status) values (640, 'trachea', '', 'Published');
insert into element (element_id, label, description, element_status) values (641, 'triple-flask', '', 'Published');
insert into element (element_id, label, description, element_status) values (642, 'ureter', '', 'Published');
insert into element (element_id, label, description, element_status) values (643, 'urethra', '', 'Published');
insert into element (element_id, label, description, element_status) values (644, 'urine', '', 'Published');
insert into element (element_id, label, description, element_status) values (645, 'uterus', '', 'Published');
insert into element (element_id, label, description, element_status) values (646, 'vaginal secretion', '', 'Published');
insert into element (element_id, label, description, element_status) values (647, 'vitreous humor', '', 'Published');
insert into element (element_id, label, description, element_status) values (648, 'vomit', '', 'Published');
insert into element (element_id, label, description, element_status) values (649, 'X-fold dilution', 'A unit that is a multiple of some standard inition of a kit of solution (e.g., 0.5x TBE or 2X PBS).', 'Published');
insert into element (element_id, label, description, element_status) values (650, 'z-factor', '', 'Published');
insert into element (element_id, label, description, element_status) values (651, 'z-prime factor', '', 'Published');
insert into element (element_id, label, description, element_status) values (731, 'selectivity endpoint', 'usually a ratio measurement', 'Published');
insert into element (element_id, label, description, element_status) values (708, 'electrical endpoint', '', 'Published');