CREATE TABLE PANEL(
    PANEL_ID                NUMBER(19, 0)     NOT NULL,
    NAME              VARCHAR2(1000 CHAR) NOT NULL,
    READY_FOR_EXTRACTION    VARCHAR2(20)      DEFAULT 'Not Ready' NOT NULL
                            CONSTRAINT CK_PANEL_EXTRACTION CHECK (ready_for_extraction IN ('Not Ready','Ready', 'Started', 'Complete')),
    VERSION                 NUMBER(38, 0)     DEFAULT 0 NOT NULL,
    DATE_CREATED            TIMESTAMP(6)      DEFAULT sysdate NOT NULL,
    LAST_UPDATED         TIMESTAMP(6) DEFAULT sysdate NOT NULL,
    MODIFIED_BY             VARCHAR2(40) NULL,
    CONSTRAINT PK_PANEL PRIMARY KEY (PANEL_ID)
)
;
CREATE SEQUENCE PANEL_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;
CREATE TABLE PANEL_ASSAY
(
    PANEL_ASSAY_ID NUMBER(19)   NOT NULL,
    ASSAY_ID         NUMBER(19)   NOT NULL,
    PANEL_ID               NUMBER(19)   NOT NULL,
    VERSION                  NUMBER(38)   DEFAULT 0 NOT NULL,
    DATE_CREATED             TIMESTAMP(6) DEFAULT sysdate NOT NULL,
    LAST_UPDATED             TIMESTAMP(6)    DEFAULT sysdate NOT NULL,
    MODIFIED_BY              VARCHAR2(40)     NULL ,
    CONSTRAINT PK_PANEL_ASSAY PRIMARY KEY (PANEL_ASSAY_ID)
)
;
CREATE SEQUENCE PANEL_ASSAY_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    NOCYCLE
    CACHE 20
    NOORDER
;
CREATE INDEX FK_PANEL_ASSAY_ASSAY
    ON PANEL_ASSAY(ASSAY_ID)
;
CREATE INDEX FK_PANEL_ASSAY_PANEL
    ON PANEL_ASSAY(PANEL_ID)
;
ALTER TABLE PANEL_ASSAY
    ADD CONSTRAINT FK_PANEL_ASSAY_ASSAY
FOREIGN KEY (ASSAY_ID)
REFERENCES ASSAY (ASSAY_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE PANEL_ASSAY
    ADD CONSTRAINT FK_PANEL_ASSAY_PANEL
FOREIGN KEY (PANEL_ID)
REFERENCES PANEL (PANEL_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE PANEL_ASSAY ADD CONSTRAINT UK_PANEL_ASSAY UNIQUE (ASSAY_ID, PANEL_ID);


