
-- Standard Alter Table SQL

ALTER TABLE STAGE RENAME TO STAGE_TREE
;
ALTER TABLE UNIT RENAME TO UNIT_TREE
;
ALTER TABLE ASSAY_DESCRIPTOR RENAME TO ASSAY_DESCRIPTOR_TREE
;
ALTER TABLE BIOLOGY_DESCRIPTOR RENAME TO BIOLOGY_DESCRIPTOR_TREE
;
ALTER TABLE ELEMENT DROP CONSTRAINT CK_ELEMENT_EXTRACTION
;
ALTER TABLE ELEMENT MODIFY(READY_FOR_EXTRACTION  DEFAULT 'Pending')
;
ALTER TABLE ELEMENT ADD CONSTRAINT CK_ELEMENT_EXTRACTION
CHECK (ready_for_extraction IN ('Pending', 'Ready', 'Started', 'Complete'))
;
ALTER TABLE INSTANCE_DESCRIPTOR RENAME TO INSTANCE_DESCRIPTOR_TREE
;
ALTER TABLE LABORATORY RENAME TO LABORATORY_TREE
;
ALTER TABLE RESULT_TYPE RENAME TO RESULT_TYPE_TREE
;
DROP INDEX IDX_ELEMENT_LOWER_LABEL
;
CREATE INDEX IDX_ELEMENT_LOWER_LABEL ON ELEMENT (LOWER("LABEL"))
;
-- Update Views SQL

CREATE VIEW ASSAY_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE ELEMENT_ID in (select ELEMENT_ID from Assay_Descriptor_Tree)
;
CREATE VIEW BIOLOGY_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select ELEMENT_ID from Biology_Descriptor_tree)
;
CREATE VIEW INSTANCE_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select ELEMENT_ID from Instance_Descriptor_tree)
;
CREATE VIEW LABORATORY_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE ELEMENT_ID in (select LABORATORY_ID from Laboratory_tree)
;
CREATE VIEW RESULT_TYPE_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select RESULT_TYPE_ID from Result_type_tree)
;
CREATE VIEW STAGE_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE el.ELEMENT_ID in (select STAGE_ID from Stage_tree)
;
CREATE VIEW UNIT_ELEMENT
(Element_ID, Element_Status, Label, Description, Abbreviation, Synonyms, Unit, External_URL, ready_for_extraction, Version, Date_Created, Last_Updated, Modified_by) AS
SELECT El.ELEMENT_ID, El.ELEMENT_STATUS, El.LABEL, El.DESCRIPTION, El.ABBREVIATION, El.SYNONYMS, El.UNIT, El.EXTERNAL_URL, El.READY_FOR_EXTRACTION, El.VERSION, El.DATE_CREATED, El.LAST_UPDATED, El.MODIFIED_BY
FROM ELEMENT El
WHERE ELEMENT_ID in (select UNIT_ID from Unit_tree)
;