/*
 * File: app/model/Assay.js
 * Date: Fri Apr 20 2012 15:44:41 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BARD.model.Assay', {
    extend: 'Ext.data.Model',

    idProperty: 'id',

    fields: [
        {
            name: 'id',
            type: 'int'
        },
        {
            name: 'assayName',
            type: 'string'
        },
        {
            name: 'assayVersion',
            type: 'string'
        },
        {
            name: 'description',
            type: 'string'
        },
        {
            name: 'designedBy',
            type: 'string'
        },
        {
            name: 'modifiedBy',
            type: 'string'
        },
        {
            name: 'dateCreated',
            type: 'date'
        },
        {
            name: 'lastUpdated',
            type: 'date'
        },
        {
            name: 'assayStatus',
            type: 'string'
        }
    ],

    proxy: {
        type: 'rest'
    },

    belongsTo: {
        associationKey: 'assayStatus',
        model: 'BARD.model.AssayStatus',
        foreignKey: 'status'
    }
});