ALTER TABLE ASSAY DROP CONSTRAINT CK_ASSAY_EXTRACTION
;
ALTER TABLE ASSAY ADD CONSTRAINT CK_ASSAY_EXTRACTION
CHECK (READY_FOR_EXTRACTION IN ('Pending','Ready', 'Started', 'Complete'))
;
ALTER TABLE ELEMENT DROP CONSTRAINT CK_ELEMENT_EXTRACTION
;
ALTER TABLE ASSAY ADD CONSTRAINT CK_ELEMENT_EXTRACTION
CHECK (READY_FOR_EXTRACTION IN ('Pending','Ready', 'Started', 'Complete'))
;
ALTER TABLE EXPERIMENT DROP CONSTRAINT CK_EXPERIMENT_EXTRACTION
;
ALTER TABLE EXPERIMENT ADD CONSTRAINT CK_EXPERIMENT_EXTRACTION
CHECK (READY_FOR_EXTRACTION IN ('Pending','Ready', 'Started', 'Complete'))
;
ALTER TABLE PROJECT DROP CONSTRAINT CK_PROJECT_EXTRACTION
;
ALTER TABLE PROJECT ADD CONSTRAINT CK_PROJECT_EXTRACTION
CHECK (READY_FOR_EXTRACTION IN ('Pending','Ready', 'Started', 'Complete'))
;
ALTER TABLE RESULT DROP CONSTRAINT CK_RESULT_EXTRACTION
;
ALTER TABLE PROJECT ADD CONSTRAINT CK_RESULT_EXTRACTION
CHECK (READY_FOR_EXTRACTION IN ('Pending','Ready', 'Started', 'Complete'))
;
