ALTER TABLE EXPERIMENT ADD CONSTRAINT CK_EXP_OWNER_ROLE_ID CHECK(OWNER_ROLE_ID IS NOT NULL) ENABLE;
ALTER TABLE ASSAY ADD CONSTRAINT CK_ASSAY_OWNER_ROLE_ID CHECK(OWNER_ROLE_ID IS NOT NULL) ENABLE;
ALTER TABLE PROJECT ADD CONSTRAINT CK_PROJECT_OWNER_ROLE_ID CHECK(OWNER_ROLE_ID IS NOT NULL) ENABLE;
ALTER TABLE PANEL ADD CONSTRAINT CK_PANEL_OWNER_ROLE_ID CHECK(OWNER_ROLE_ID IS NOT NULL) ENABLE;