
-- Sequence Alter SQL

-- Standard Alter Table SQL
-- rename the primary key for Step_context
ALTER TABLE STEP_CONTEXT_ITEM DROP CONSTRAINT FK_STEP_CNTXT_ITM_STEP_CNTXT
;
ALTER TABLE STEP_CONTEXT DROP PRIMARY KEY DROP INDEX
;
ALTER TABLE STEP_CONTEXT ADD CONSTRAINT PK_STEP_CONTEXT
PRIMARY KEY (STEP_CONTEXT_ID)
;
ALTER TABLE STEP_CONTEXT_ITEM ADD CONSTRAINT FK_STEP_CNTXT_ITM_STEP_CNTXT
FOREIGN KEY (STEP_CONTEXT_ID)
REFERENCES STEP_CONTEXT (STEP_CONTEXT_ID)
ENABLE VALIDATE
;

---------------------------------------------------------------------------
-- widen full_path col to 3000 for tree tables
ALTER TABLE ASSAY_DESCRIPTOR_TREE MODIFY(FULL_PATH  VARCHAR2(3000))
;
ALTER TABLE BIOLOGY_DESCRIPTOR_TREE MODIFY(FULL_PATH  VARCHAR2(3000))
;
ALTER TABLE INSTANCE_DESCRIPTOR_TREE MODIFY(FULL_PATH  VARCHAR2(3000))
;
ALTER TABLE UNIT_TREE MODIFY(FULL_PATH  VARCHAR2(3000))
;
ALTER TABLE STAGE_TREE MODIFY(FULL_PATH  VARCHAR2(3000))
;
ALTER TABLE RESULT_TYPE_TREE MODIFY(FULL_PATH  VARCHAR2(3000))
;

-- make self referencing measure fk defferable
ALTER TABLE MEASURE DROP CONSTRAINT FK_MEASURE_PARENT_MEASURE_ID
;
ALTER TABLE MEASURE ADD CONSTRAINT FK_MEASURE_PARENT_MEASURE_ID
FOREIGN KEY (PARENT_MEASURE_ID)
REFERENCES MEASURE (MEASURE_ID)
DEFERRABLE INITIALLY DEFERRED ENABLE VALIDATE
;
-- add a comment
COMMENT ON TABLE PROJECT_STEP IS
'The annotations (context items) for a step show the annotations of the incoming arrowhead on the edge between the experiments and the "follows" experiment.  Thus the annotations can refer to the experiment or the step (aka decision) that instigated the experiment.  Bear in mind that the "follows" experiment can be null, i.e. this the experiment does not have a predecessor.  Primary screens tend to have this characteristic.'
;
ALTER TABLE RESULT_HIERARCHY MODIFY(HIERARCHY_TYPE  VARCHAR2(20))
;

--Drop Constraint, Rename and Create Table SQL
ALTER TABLE ONTOLOGY_ITEM DROP CONSTRAINT FK_ONTOLOGY_ITEM_ELEMENT
;
ALTER TABLE ONTOLOGY_ITEM DROP CONSTRAINT FK_ONTOLOGY_ITEM_ONTOLOGY
;
ALTER TABLE ONTOLOGY_ITEM DROP PRIMARY KEY DROP INDEX
;
DROP INDEX FK_ONTOLOGY_ITEM_ONTOLOGY
;
DROP INDEX FK_ONTOLOGY_ITEM_ELEMENT
;
ALTER TABLE ONTOLOGY_ITEM RENAME TO ONTOLOGY_I_11262012222421000
;
CREATE TABLE ONTOLOGY_ITEM
(
    ONTOLOGY_ITEM_ID NUMBER(19)   NOT NULL,
    ONTOLOGY_ID      NUMBER(19)   NOT NULL,
    ELEMENT_ID       NUMBER(19)       NULL,
    ITEM_REFERENCE   VARCHAR2(20)     NULL,
    VERSION          NUMBER(38)   DEFAULT 0 NOT NULL,
    DATE_CREATED     TIMESTAMP(6) DEFAULT sysdate NOT NULL,
    LAST_UPDATED     TIMESTAMP(6)     NULL,
    MODIFIED_BY      VARCHAR2(40)     NULL
)
;
COMMENT ON COLUMN ONTOLOGY_ITEM.ITEM_REFERENCE IS
'Concatenate this with the Ontology.system_URL for a full URI for the item'
;
-- create some missing tables
CREATE TABLE DICTIONARY_TREE
(
    NODE_ID        NUMBER(19)     NOT NULL,
    PARENT_NODE_ID NUMBER(19)         NULL,
    ELEMENT_ID     NUMBER(19)     NOT NULL,
    ELEMENT_STATUS VARCHAR2(20)   NOT NULL,
    LABEL          VARCHAR2(128)  NOT NULL,
    IS_LEAF        CHAR(1)        NOT NULL,
    FULL_PATH      VARCHAR2(3000)     NULL,
    DESCRIPTION    VARCHAR2(1000)     NULL,
    ABBREVIATION   VARCHAR2(20)       NULL,
    SYNONYMS       VARCHAR2(1000)     NULL,
    EXTERNAL_URL   VARCHAR2(1000)     NULL,
    UNIT_ID        NUMBER(19)         NULL
)
;
ALTER TABLE DICTIONARY_TREE
    ADD CONSTRAINT PK_DICTIONARY_TREE
    PRIMARY KEY (NODE_ID)
    USING INDEX STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
;
CREATE TABLE STATS_MODIFIER_TREE
(
    NODE_ID        NUMBER(19)     NOT NULL,
    PARENT_NODE_ID NUMBER(19)         NULL,
    ELEMENT_ID     NUMBER(19)     NOT NULL,
    ELEMENT_STATUS VARCHAR2(20)   NOT NULL,
    LABEL          VARCHAR2(128)  NOT NULL,
    IS_LEAF        CHAR(1)        NOT NULL,
    FULL_PATH      VARCHAR2(3000)     NULL,
    DESCRIPTION    VARCHAR2(1000)     NULL,
    ABBREVIATION   VARCHAR2(20)       NULL,
    SYNONYMS       VARCHAR2(1000)     NULL,
    EXTERNAL_URL   VARCHAR2(1000)     NULL,
    UNIT_ID        NUMBER(19)         NULL
)
;
ALTER TABLE STATS_MODIFIER_TREE
    ADD CONSTRAINT PK_STATS_MODIFIER
    PRIMARY KEY (NODE_ID)
    USING INDEX STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
;

-- Insert Data SQL

ALTER TABLE UNIT_TREE LOGGING
;
ALTER SESSION ENABLE PARALLEL DML
;
INSERT INTO ONTOLOGY_ITEM(
                         ONTOLOGY_ITEM_ID,
                         ONTOLOGY_ID,
                         ELEMENT_ID,
                         ITEM_REFERENCE,
                         VERSION,
                         DATE_CREATED,
                         LAST_UPDATED,
                         MODIFIED_BY
                        )
                  SELECT
                         ONTOLOGY_ITEM_ID,
                         ONTOLOGY_ID,
                         ELEMENT_ID,
                         ITEM_REFERENCE,
                         VERSION,
                         DATE_CREATED,
                         LAST_UPDATED,
                         MODIFIED_BY
                    FROM ONTOLOGY_I_11262012222421000
;
ALTER TABLE ONTOLOGY_ITEM LOGGING
;
ALTER TABLE STAGE_TREE LOGGING
;

-- Add Indexes SQL

CREATE INDEX FK_ONTOLOGY_ITEM_ONTOLOGY
    ON ONTOLOGY_ITEM(ONTOLOGY_ID)
;
CREATE INDEX FK_ONTOLOGY_ITEM_ELEMENT
    ON ONTOLOGY_ITEM(ELEMENT_ID)
;

-- Add Constraint SQL

ALTER TABLE ONTOLOGY_ITEM ADD CONSTRAINT PK_ONTOLOGY_ITEM
PRIMARY KEY (ONTOLOGY_ITEM_ID)
;
-- Add Dependencies SQL

ALTER VIEW UNIT_ELEMENT COMPILE
;
ALTER VIEW STAGE_ELEMENT COMPILE
;

-- Alter Index SQL

CREATE INDEX IDX_STEP_ITEM_IDX_VAL
    ON STEP_CONTEXT_ITEM(EXT_VALUE_ID)
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE UNIQUE INDEX AK_MEASURE
    ON MEASURE(ASSAY_ID,RESULT_TYPE_ID,STATS_MODIFIER_ID,PARENT_MEASURE_ID)
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX IDX_R_CONTEXT_ITEM_EXT_VAL
    ON RSLT_CONTEXT_ITEM(EXT_VALUE_ID)
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX FK_DICTIONARY_TREE_PARENT
    ON DICTIONARY_TREE(PARENT_NODE_ID)
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
CREATE INDEX FK_STATS_MODIFIER_PARENT
    ON STATS_MODIFIER_TREE(PARENT_NODE_ID)
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;

-- Add Referencing Foreign Keys SQL

ALTER TABLE DICTIONARY_TREE
    ADD CONSTRAINT FK_DICTIONARY_TREE_PARENT
FOREIGN KEY (PARENT_NODE_ID)
REFERENCES DICTIONARY_TREE (NODE_ID)
ENABLE VALIDATE
;
ALTER TABLE STATS_MODIFIER_TREE
    ADD CONSTRAINT FK_STATS_MODIFIER_PARENT
FOREIGN KEY (PARENT_NODE_ID)
REFERENCES STATS_MODIFIER_TREE (NODE_ID)
ENABLE VALIDATE
;
ALTER TABLE ONTOLOGY_ITEM ADD CONSTRAINT FK_ONTOLOGY_ITEM_ELEMENT
FOREIGN KEY (ELEMENT_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE ONTOLOGY_ITEM ADD CONSTRAINT FK_ONTOLOGY_ITEM_ONTOLOGY
FOREIGN KEY (ONTOLOGY_ID)
REFERENCES ONTOLOGY (ONTOLOGY_ID)
ENABLE VALIDATE
;
