CREATE TABLE DOWN_TIME_SCHEDULER
(
    DOWN_TIME_SCHEDULER_ID NUMBER(19)    NOT NULL,
    DISPLAY_VALUE VARCHAR2(100)    NOT NULL,
    CREATED_BY             VARCHAR2(256) NOT NULL,
    DOWN_TIME            TIMESTAMP(6)   NOT NULL,
    DATE_CREATED          TIMESTAMP(6)  DEFAULT sysdate NOT NULL,
    LAST_UPDATED          TIMESTAMP(6)  DEFAULT sysdate NOT NULL,
    VERSION NUMBER(19)   NOT NULL
)
;
ALTER TABLE DOWN_TIME_SCHEDULER ADD CONSTRAINT PK_DOWN_TIME_SCHEDULER PRIMARY KEY (DOWN_TIME_SCHEDULER_ID)
;
CREATE SEQUENCE DOWN_TIME_SCHEDULER_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    NOMAXVALUE
    CACHE 20
    NOORDER
;