ALTER TABLE EXPERIMENT DROP CONSTRAINT FK_EXP_OWNER_ROLE_ID
;
ALTER TABLE ASSAY DROP CONSTRAINT FK_ASSAY_OWNER_ROLE_ID
;
ALTER TABLE PANEL DROP CONSTRAINT FK_PANEL_OWNER_ROLE_ID
;
ALTER TABLE PROJECT DROP CONSTRAINT FK_PROJECT_OWNER_ROLE_ID
;
ALTER TABLE EXPERIMENT DROP ( OWNER_ROLE_ID )
;
ALTER TABLE ASSAY DROP ( OWNER_ROLE_ID )
;
ALTER TABLE PANEL DROP ( OWNER_ROLE_ID )
;
ALTER TABLE PROJECT DROP ( OWNER_ROLE_ID )
;
