-- Drop Constraint, Rename and Create Table SQL
ALTER TABLE ELEMENT
    ADD (EXPECTED_VALUE_TYPE  VARCHAR2(40)   DEFAULT 'none' NOT NULL,
         ADD_CHILD_METHOD     VARCHAR2(20)   DEFAULT 'no'   NOT NULL
        )
;

ALTER TABLE ELEMENT
    MODIFY READY_FOR_EXTRACTION DEFAULT 'Ready'
;

ALTER TABLE ELEMENT ADD CONSTRAINT CK_ELEMENT_EXPECTED_VALUE_TYPE
CHECK (Expected_Value_Type in ('numeric', 'element', 'external ontology', 'free text', 'none'))
;
ALTER TABLE ELEMENT ADD CONSTRAINT CK_ELEMENT_ADD_CHILD_METHOD
CHECK (Add_Child_Method in ('RDM request', 'direct', 'no'))
;

ALTER VIEW ASSAY_ELEMENT COMPILE
;
ALTER VIEW BIOLOGY_ELEMENT COMPILE
;
ALTER VIEW INSTANCE_ELEMENT COMPILE
;
ALTER VIEW LABORATORY_ELEMENT COMPILE
;
ALTER VIEW RESULT_TYPE_ELEMENT COMPILE
;
ALTER VIEW STAGE_ELEMENT COMPILE
;
ALTER VIEW UNIT_ELEMENT COMPILE
;

CREATE UNIQUE INDEX AK_ELEMENT_BARD_URI
    ON ELEMENT(BARD_URI)
STORAGE(BUFFER_POOL DEFAULT)
NOPARALLEL
NOCOMPRESS
;
