/*
 * File: app/store/assayStatusStore.js
 * Date: Mon Apr 23 2012 15:05:42 GMT-0400 (EDT)
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BARD.store.assayStatusStore', {
    extend: 'Ext.data.Store',
    alias: 'store.assayStatusStore',

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'assayStatusStore',
            autoCreated: 'false',
            proxy: {
                type: 'ajax',
                url: 'api/assay-status',
                reader: {
                    type: 'json',
                    root: 'statuses'
                }
            },
            fields: [
                {
                    name: 'id'
                },
                {
                    name: 'status'
                }
            ]
        }, cfg)]);
    }
});