/*
 * File: app/store/StageStore.js
 * Date: Tue Apr 24 2012 14:22:06 GMT-0400 (EDT)
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BARD.store.StageStore', {
    extend: 'Ext.data.Store',
    requires: [
        'BARD.model.Stage'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'StageStore',
            model: 'BARD.model.Stage',
            proxy: {
                type: 'ajax',
                url: 'api/stage',
                reader: {
                    type: 'json',
                    root: 'data'
                }
            }
        }, cfg)]);
    }
});