-- Add Indexes SQL
CREATE INDEX FK_UNIT_PARENT_SELF
    ON UNIT_TREE(PARENT_NODE_ID)
;
CREATE INDEX FK_A_CONTEXT_ITEM_ATTRIBUTE
    ON ASSAY_CONTEXT_ITEM(ATTRIBUTE_ID)
;
CREATE UNIQUE INDEX AK_ASSAY_CONTEXT_ITEM
    ON ASSAY_CONTEXT_ITEM(ASSAY_CONTEXT_ID,DISPLAY_ORDER,ATTRIBUTE_ID,ATTRIBUTE_TYPE,VALUE_DISPLAY)
;
CREATE INDEX FK_A_CONTEXT_ITEM_A_CONTEXT
    ON ASSAY_CONTEXT_ITEM(ASSAY_CONTEXT_ID)
;
CREATE INDEX FK_ASSAY_DESCRIPTOR_PARENT_SLF
    ON ASSAY_DESCRIPTOR_TREE(PARENT_NODE_ID)
;
CREATE INDEX FK_BIOLOGY_DESCRIPTOR_PRNT_SLF
    ON BIOLOGY_DESCRIPTOR_TREE(PARENT_NODE_ID)
;
CREATE INDEX IDX_ELEMENT_LOWER_LABEL
    ON ELEMENT(LOWER("LABEL"))
;
CREATE INDEX FK_INSTANCE_DESCRIPTR_PRNT_SLF
    ON INSTANCE_DESCRIPTOR_TREE(PARENT_NODE_ID)
;
CREATE INDEX FK_MEASURE_RESULT_TYPE
    ON MEASURE(RESULT_TYPE_ID)
;
CREATE INDEX FK_MEASURE_ASSAY
    ON MEASURE(ASSAY_ID)
;
CREATE INDEX FK_MEASURE_PARENT_MEASURE_ID
    ON MEASURE(PARENT_MEASURE_ID)
;
CREATE INDEX FK_PROJECT_STEP_ITEM_ATTRIBUTE
    ON PROJECT_CONTEXT_ITEM(ATTRIBUTE_ID)
;
CREATE INDEX FK_PROJECT_STEP_ITEM_VALUE
    ON PROJECT_CONTEXT_ITEM(VALUE_ID)
;
CREATE BITMAP INDEX FK_RESULT_EXPERIMENT
    ON RESULT(EXPERIMENT_ID)
;
CREATE BITMAP INDEX FK_RESULT_RESULT_TYPE
    ON RESULT(RESULT_TYPE_ID)
;
CREATE INDEX FK_RESULT_HIERARCHY_RSLT_PRNT
    ON RESULT_HIERARCHY(RESULT_ID)
;
CREATE INDEX FK_RESULT_HIERARCHY_RESULT
    ON RESULT_HIERARCHY(PARENT_RESULT_ID)
;
CREATE INDEX FK_RESULT_TYPE_PARENT_SELF
    ON RESULT_TYPE_TREE(PARENT_NODE_ID)
;
-- Add Constraint SQL
ALTER TABLE STAGE_TREE ADD CONSTRAINT PK_STAGE
PRIMARY KEY (NODE_ID)
;
ALTER TABLE UNIT_CONVERSION ADD CONSTRAINT PK_UNIT_CONVERSION
PRIMARY KEY (UNIT_CONVERSION_ID)
;
ALTER TABLE UNIT_CONVERSION ADD CONSTRAINT AK_UNIT_CONVERSION
UNIQUE (FROM_UNIT_ID,TO_UNIT_ID)
;
ALTER TABLE UNIT_TREE ADD CONSTRAINT PK_UNIT
PRIMARY KEY (NODE_ID)
;
ALTER TABLE ASSAY_CONTEXT ADD CONSTRAINT PK_ASSAY_CONTEXT
PRIMARY KEY (ASSAY_CONTEXT_ID)
;
ALTER TABLE ASSAY_CONTEXT_ITEM ADD CONSTRAINT PK_ASSAY_CONTEXT_ITEM
PRIMARY KEY (ASSAY_CONTEXT_ITEM_ID)
;
ALTER TABLE ASSAY_CONTEXT_ITEM ADD CONSTRAINT CK_ASSAY_CONTEXT_ITEM_QALFR
CHECK (QUALIFIER IN ('= ', '< ', '<=', '> ', '>=', '<<', '>>', '~ '))
;
ALTER TABLE ASSAY_CONTEXT_ITEM ADD CONSTRAINT CK_ATTRIBUTE_TYPE
CHECK (Attribute_Type in ('Fixed', 'List', 'Range', 'Free'))
;
ALTER TABLE ASSAY_DESCRIPTOR_TREE ADD CONSTRAINT PK_ASSAY_DESCRIPTOR
PRIMARY KEY (NODE_ID)
;
ALTER TABLE BIOLOGY_DESCRIPTOR_TREE ADD CONSTRAINT PK_BIOLOGY_DESCRIPTOR
PRIMARY KEY (NODE_ID)
-- ;
-- ALTER TABLE ELEMENT ADD CONSTRAINT PK_ELEMENT
-- PRIMARY KEY (ELEMENT_ID)
;
ALTER TABLE ELEMENT ADD CONSTRAINT AK_ELEMENT_LABEL
UNIQUE (LABEL)
;
ALTER TABLE ELEMENT ADD CONSTRAINT CK_ELEMENT_EXTRACTION
CHECK (ready_for_extraction IN ('Pending', 'Ready', 'Started', 'Complete'))
;
ALTER TABLE ELEMENT ADD CONSTRAINT CK_ELEMENT_STATUS
CHECK (Element_Status IN ('Pending', 'Published', 'Deprecated', 'Retired'))
;
ALTER TABLE INSTANCE_DESCRIPTOR_TREE ADD CONSTRAINT PK_INSTANCE_DESCRIPTOR
PRIMARY KEY (NODE_ID)
;
ALTER TABLE MEASURE ADD CONSTRAINT PK_MEASURE
PRIMARY KEY (MEASURE_ID)
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT PK_PROJECT_CONTEXT_ITEM
PRIMARY KEY (PROJECT_CONTEXT_ITEM_ID)
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT CK_PRJCT_CNTXT_ITEM_QUALIFIER
CHECK (Qualifier IN ('= ', '< ', '<=', '> ', '>=', '<<', '>>', '~ '))
;
ALTER TABLE RESULT ADD CONSTRAINT PK_RESULT
PRIMARY KEY (RESULT_ID)
;
ALTER TABLE RESULT ADD CONSTRAINT CK_RESULT_EXTRACTION
CHECK (ready_for_extraction IN ('Pending', 'Ready', 'Started', 'Complete'))
;
ALTER TABLE RESULT ADD CONSTRAINT CK_RESULT_QUALIFIER
CHECK (Qualifier IN ('= ', '< ', '<=', '> ', '>=', '<<', '>>', '~ '))
;
ALTER TABLE RESULT ADD CONSTRAINT CK_RESULT_STATUS
CHECK (Result_Status IN ('Pending', 'Approved', 'Rejected', 'Mark for Deletion'))
;
ALTER TABLE RESULT_HIERARCHY ADD CONSTRAINT PK_RESULT_HIERARCHY
PRIMARY KEY (RESULT_HIERARCHY_ID)
;
ALTER TABLE RESULT_HIERARCHY ADD CONSTRAINT CK_RESULT_HIERARCHY_TYPE
CHECK (HIERARCHY_TYPE in ('Child', 'Derives'))
;
ALTER TABLE RESULT_TYPE_TREE ADD CONSTRAINT PK_RESULT_TYPE
PRIMARY KEY (NODE_ID)
;
ALTER TABLE RSLT_CONTEXT_ITEM ADD CONSTRAINT PK_RSLT_CONTEXT_ITEM
PRIMARY KEY (RSLT_CONTEXT_ITEM_ID)
;
ALTER TABLE RSLT_CONTEXT_ITEM ADD CONSTRAINT CK_RSLT_CONTEXT_ITEM_QULFR
CHECK (Qualifier IN ('= ', '< ', '<=', '> ', '>=', '<<', '>>', '~ '))
;
-- Alter Index SQL
CREATE INDEX FK_A_CONTEXT_ITEM_VALUE
    ON ASSAY_CONTEXT_ITEM(VALUE_ID)
;
CREATE UNIQUE INDEX AK_EXT_REFERENCE
    ON EXTERNAL_REFERENCE(EXTERNAL_SYSTEM_ID,EXPERIMENT_ID,PROJECT_ID,EXT_ASSAY_REF)
;
ALTER INDEX FK_PROJECT_STEP_ITEM_ATTRIBUTE
    RENAME  TO FK_PRJCT_CNTXT_ITEM_ATTRIBUTE
;
ALTER INDEX FK_PROJECT_STEP_ITEM_VALUE
    RENAME  TO FK_PRJCT_CNTXT_ITEM_VALUE
;
CREATE INDEX FK_PRJCT_CNTXT_ITEM_PRCT_CNTXT
    ON PROJECT_CONTEXT_ITEM(PROJECT_CONTEXT_ID)
;
CREATE INDEX FK_R_CONTEXT_ITEM_RESULT
    ON RSLT_CONTEXT_ITEM(RESULT_ID)
;
CREATE INDEX FK_R_CONTEXT_ITEM_VALUE
    ON RSLT_CONTEXT_ITEM(VALUE_ID)
;
CREATE INDEX FK_R_CONTEXT_ITEM_ATTRIBUTE
    ON RSLT_CONTEXT_ITEM(ATTRIBUTE_ID)
;
CREATE INDEX FK_STEP_ITEM_STEP_CONTEXT
    ON STEP_CONTEXT_ITEM(STEP_CONTEXT_ID)
;
CREATE INDEX FK_STEP_ITEM_ATTRIBUTE
    ON STEP_CONTEXT_ITEM(ATTRIBUTE_ID)
;
CREATE INDEX FK_STEP_ITEM_VALUE
    ON STEP_CONTEXT_ITEM(VALUE_ID)
;
CREATE UNIQUE INDEX AK_TEAM
    ON TEAM(TEAM_NAME)
;
CREATE UNIQUE INDEX AK_TEAM_MEMBER
    ON TEAM_MEMBER(TEAM_ID,PERSON_ROLE_ID)
;
CREATE INDEX FK_TEAM_MEMBER_TEAM
    ON TEAM_MEMBER(TEAM_ID)
;
CREATE INDEX FK_TEAM_MEMBER_PERSON_ROLE
    ON TEAM_MEMBER(PERSON_ROLE_ID)
;
CREATE INDEX FK_ACM_ASSAY_CONTEXT
    ON ASSAY_CONTEXT_MEASURE(ASSAY_CONTEXT_ID)
;
CREATE INDEX FK_ACM_MEASURE
    ON ASSAY_CONTEXT_MEASURE(MEASURE_ID)
;
CREATE INDEX FK_E_CONTEXT_ITEM_EXPRMT_CNTXT
    ON EXPRMT_CONTEXT_ITEM(EXPRMT_CONTEXT_ID)
;
CREATE INDEX FK_E_CONTEXT_ITEM_ATTRIBUTE
    ON EXPRMT_CONTEXT_ITEM(ATTRIBUTE_ID)
;
CREATE INDEX FK_E_CONTEXT_ITEM_VALUE
    ON EXPRMT_CONTEXT_ITEM(VALUE_ID)
;
CREATE UNIQUE INDEX AK_FAVORITE
    ON FAVORITE(PERSON_ID,FAVORITE_NAME)
;
CREATE INDEX FK_FAVORITE_PERSON
    ON FAVORITE(PERSON_ID)
;
CREATE UNIQUE INDEX AK_PERSON
    ON PERSON(USERNAME)
;
CREATE UNIQUE INDEX AK_PERSON_ROLE
    ON PERSON_ROLE(ROLE_ID,PERSON_ID)
;
CREATE INDEX FK_PERSON_ROLE_PERSON
    ON PERSON_ROLE(PERSON_ID)
;
CREATE INDEX FK_PERSON_ROLE_ROLE
    ON PERSON_ROLE(ROLE_ID)
;
CREATE INDEX FK_PROJECT_DOCUMENT_PROJECT
    ON PROJECT_DOCUMENT(PROJECT_ID)
;
CREATE UNIQUE INDEX AK_ROLE
    ON ROLE(AUTHORITY)
;
-- Add Referencing Foreign Keys SQL
ALTER TABLE ASSAY_CONTEXT_ITEM ADD CONSTRAINT FK_A_CONTEXT_ITEM_A_CONTEXT
FOREIGN KEY (ASSAY_CONTEXT_ID)
REFERENCES ASSAY_CONTEXT (ASSAY_CONTEXT_ID)
ENABLE VALIDATE
;
ALTER TABLE ASSAY_CONTEXT_ITEM ADD CONSTRAINT FK_A_CONTEXT_ITEM_ATTRIBUTE
FOREIGN KEY (ATTRIBUTE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE ASSAY_CONTEXT_ITEM ADD CONSTRAINT FK_A_CONTEXT_ITEM_VALUE
FOREIGN KEY (VALUE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE ELEMENT_HIERARCHY ADD CONSTRAINT FK_E_HIERARCHY_CHILD_ELEM_ID
FOREIGN KEY (CHILD_ELEMENT_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE ELEMENT_HIERARCHY ADD CONSTRAINT FK_E_HIERARCHY_PARENT_ELEM_ID
FOREIGN KEY (PARENT_ELEMENT_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE MEASURE ADD CONSTRAINT FK_MEASURE_ELEMENT_UNIT
FOREIGN KEY (ENTRY_UNIT_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE MEASURE ADD CONSTRAINT FK_MEASURE_RESULT_TYPE
FOREIGN KEY (RESULT_TYPE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE ONTOLOGY_ITEM ADD CONSTRAINT FK_ONTOLOGY_ITEM_ELEMENT
FOREIGN KEY (ELEMENT_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT FK_PRJCT_CNTXT_ITEM_ATTRIBUTE
FOREIGN KEY (ATTRIBUTE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT FK_PRJCT_CNTXT_ITEM_VALUE
FOREIGN KEY (VALUE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE RESULT ADD CONSTRAINT FK_RESULT_RESULT_TYPE
FOREIGN KEY (RESULT_TYPE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE RSLT_CONTEXT_ITEM ADD CONSTRAINT FK_R_CONTEXT_ITEM_ATTRIBUTE
FOREIGN KEY (ATTRIBUTE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE RSLT_CONTEXT_ITEM ADD CONSTRAINT FK_R_CONTEXT_ITEM_VALUE
FOREIGN KEY (VALUE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE TREE_ROOT ADD CONSTRAINT FK_TREE_ROOT_ELEMENT
FOREIGN KEY (ELEMENT_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE UNIT_CONVERSION ADD CONSTRAINT FK_UNIT_CONVERSN_FRM_UNT_ELMNT
FOREIGN KEY (FROM_UNIT_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE UNIT_CONVERSION ADD CONSTRAINT FK_UNIT_CONVERSN_TO_UNT_ELMNT
FOREIGN KEY (TO_UNIT_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE RESULT_HIERARCHY ADD CONSTRAINT FK_RESULT_HIERARCHY_RSLT_PRNT
FOREIGN KEY (PARENT_RESULT_ID)
REFERENCES RESULT (RESULT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE RESULT_HIERARCHY ADD CONSTRAINT FK_RESULT_HIERARCHY_RESULT
FOREIGN KEY (RESULT_ID)
REFERENCES RESULT (RESULT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE RSLT_CONTEXT_ITEM ADD CONSTRAINT FK_R_CONTEXT_ITEM_RESULT
FOREIGN KEY (RESULT_ID)
REFERENCES RESULT (RESULT_ID)
ENABLE VALIDATE
;
ALTER TABLE STEP_CONTEXT
    ADD CONSTRAINT FK_STEP_CNTXT_STEP
FOREIGN KEY (PROJECT_STEP_ID)
REFERENCES PROJECT_STEP (PROJECT_STEP_ID)
ENABLE VALIDATE
;
ALTER TABLE STEP_CONTEXT_ITEM
    ADD CONSTRAINT FK_STEP_CNTXT_ITM_STEP_CNTXT
FOREIGN KEY (STEP_CONTEXT_ID)
REFERENCES STEP_CONTEXT (STEP_CONTEXT_ID)
ENABLE VALIDATE
;
ALTER TABLE STEP_CONTEXT_ITEM
    ADD CONSTRAINT FK_STEP_CNTXT_ITEM_VALUE
FOREIGN KEY (ATTRIBUTE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE STEP_CONTEXT_ITEM
    ADD CONSTRAINT FK_STEP_CNTXT_ITEM_ATTR
FOREIGN KEY (VALUE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE TEAM_MEMBER
    ADD CONSTRAINT FK_TEAM_MEMBER_TEAM
FOREIGN KEY (TEAM_ID)
REFERENCES TEAM (TEAM_ID)
ENABLE VALIDATE
;
ALTER TABLE TEAM_MEMBER
    ADD CONSTRAINT FK_TEAM_MEMBER_MEMBER_ROLE
FOREIGN KEY (PERSON_ROLE_ID)
REFERENCES PERSON_ROLE (PERSON_ROLE_ID)
ENABLE VALIDATE
;
ALTER TABLE ASSAY_CONTEXT_MEASURE
    ADD CONSTRAINT FK_ACM_ASSAY_CONTEXT
FOREIGN KEY (ASSAY_CONTEXT_ID)
REFERENCES ASSAY_CONTEXT (ASSAY_CONTEXT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE ASSAY_CONTEXT_MEASURE
    ADD CONSTRAINT FK_ACM_MEASURE
FOREIGN KEY (MEASURE_ID)
REFERENCES MEASURE (MEASURE_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE EXPRMT_CONTEXT
    ADD CONSTRAINT FK_E_CNTXT_EXPERIMENT
FOREIGN KEY (EXPERIMENT_ID)
REFERENCES EXPERIMENT (EXPERIMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE EXPRMT_CONTEXT_ITEM
    ADD CONSTRAINT FK_E_CNTXT_ITM_VALUE
FOREIGN KEY (VALUE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE EXPRMT_CONTEXT_ITEM
    ADD CONSTRAINT FK_E_CNTXT_ITM_EXPRMT_CNTXT
FOREIGN KEY (EXPRMT_CONTEXT_ID)
REFERENCES EXPRMT_CONTEXT (EXPRMT_CONTEXT_ID)
ENABLE VALIDATE
;
ALTER TABLE EXPRMT_CONTEXT_ITEM
    ADD CONSTRAINT FK_E_CNTXT_ITM_ATTRIBUTE
FOREIGN KEY (ATTRIBUTE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE FAVORITE
    ADD CONSTRAINT FK_FAVORITE_PERSON
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (PERSON_ID)
ENABLE VALIDATE
;
ALTER TABLE PERSON_ROLE
    ADD CONSTRAINT FK_PERSON_ROLE_ROLE
FOREIGN KEY (ROLE_ID)
REFERENCES ROLE (ROLE_ID)
ENABLE VALIDATE
;
ALTER TABLE PERSON_ROLE
    ADD CONSTRAINT FK_PERSON_ROLE_PERSON
FOREIGN KEY (PERSON_ID)
REFERENCES PERSON (PERSON_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT
    ADD CONSTRAINT FK_PRJCT_CNTXT_PROJECT
FOREIGN KEY (PROJECT_ID)
REFERENCES PROJECT (PROJECT_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_DOCUMENT
    ADD CONSTRAINT FK_PROJECT_DOCUMENT_PROJECT
FOREIGN KEY (PROJECT_ID)
REFERENCES PROJECT (PROJECT_ID)
ENABLE VALIDATE
;
ALTER TABLE STAGE_TREE ADD CONSTRAINT FK_STAGE_PARENT_NODE_ID
FOREIGN KEY (PARENT_NODE_ID)
REFERENCES STAGE_TREE (NODE_ID)
ENABLE VALIDATE
;
ALTER TABLE UNIT_TREE ADD CONSTRAINT FK_UNIT_PARENT_SELF
FOREIGN KEY (PARENT_NODE_ID)
REFERENCES UNIT_TREE (NODE_ID)
ENABLE VALIDATE
;
ALTER TABLE ASSAY_CONTEXT ADD CONSTRAINT FK_ASSAY_CONTEXT_ASSAY
FOREIGN KEY (ASSAY_ID)
REFERENCES ASSAY (ASSAY_ID)
ENABLE VALIDATE
;
ALTER TABLE ASSAY_DESCRIPTOR_TREE ADD CONSTRAINT FK_ASSAY_DESCRIPTOR_PARENT_SLF
FOREIGN KEY (PARENT_NODE_ID)
REFERENCES ASSAY_DESCRIPTOR_TREE (NODE_ID)
ENABLE VALIDATE
;
ALTER TABLE BIOLOGY_DESCRIPTOR_TREE ADD CONSTRAINT FK_BIOLOGY_DESCRIPTOR_PRNT_SLF
FOREIGN KEY (PARENT_NODE_ID)
REFERENCES BIOLOGY_DESCRIPTOR_TREE (NODE_ID)
ENABLE VALIDATE
;
-- ALTER TABLE ELEMENT ADD CONSTRAINT FK_ELEMENT_UNIT
-- FOREIGN KEY (UNIT_ID)
-- REFERENCES ELEMENT (ELEMENT_ID)
-- ;
ALTER TABLE INSTANCE_DESCRIPTOR_TREE ADD CONSTRAINT FK_INSTANCE_DESCRIPTR_PRNT_SLF
FOREIGN KEY (PARENT_NODE_ID)
REFERENCES INSTANCE_DESCRIPTOR_TREE (NODE_ID)
ENABLE VALIDATE
;
ALTER TABLE MEASURE ADD CONSTRAINT FK_MEASURE_ASSAY
FOREIGN KEY (ASSAY_ID)
REFERENCES ASSAY (ASSAY_ID)
ENABLE VALIDATE
;
ALTER TABLE MEASURE ADD CONSTRAINT FK_MEASURE_PARENT_MEASURE_ID
FOREIGN KEY (PARENT_MEASURE_ID)
REFERENCES MEASURE (MEASURE_ID)
ENABLE VALIDATE
;
ALTER TABLE PROJECT_CONTEXT_ITEM ADD CONSTRAINT FK_PRJCT_CNTXT_ITM_PRJCT_CNTXT
FOREIGN KEY (PROJECT_CONTEXT_ID)
REFERENCES PROJECT_CONTEXT (PROJECT_CONTEXT_ID)
ENABLE VALIDATE
;
ALTER TABLE RESULT ADD CONSTRAINT FK_RESULT_EXPERIMENT
FOREIGN KEY (EXPERIMENT_ID)
REFERENCES EXPERIMENT (EXPERIMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE RESULT_TYPE_TREE ADD CONSTRAINT FK_RESULT_TYPE_PARENT_SELF
FOREIGN KEY (PARENT_NODE_ID)
REFERENCES RESULT_TYPE_TREE (NODE_ID)
ENABLE VALIDATE
;