package db

/**
 * this class holds all the database queries to fetch data.
 * @author Muhammad.Rafique
 * Date Created: 13/11/25
 */
class ExperimentQueries {
	final static String EXPERIMENT_SUMMARY_BYID = "SELECT E.EXPERIMENT_ID AS EID, E.EXPERIMENT_STATUS AS Status, E.EXPERIMENT_NAME AS Name, E.DESCRIPTION AS Description, to_char(E.RUN_DATE_FROM, 'MM/DD/YYYY') as RunDateFrom, to_char(E.RUN_DATE_TO, 'MM/DD/YYYY') as RunDateTo, to_char(E.DATE_CREATED, 'MM/DD/YYYY') AS DateCreated, to_char(E.LAST_UPDATED, 'MM/DD/YYYY') AS LastUpdated, E.MODIFIED_BY AS ModifiedBy FROM EXPERIMENT E WHERE E.EXPERIMENT_ID = ?";
	final static String EXPERIMENT_CONTEXTS = "SELECT EC.CONTEXT_NAME ContextName FROM EXPRMT_CONTEXT EC WHERE EC.EXPERIMENT_ID = ? AND EC.CONTEXT_TYPE = ?"
	final static String EXPERIMENT_CONTEXT_ITEMS = "SELECT E.LABEL AttributeLabel, ECI.VALUE_DISPLAY ValueDisplay FROM EXPRMT_CONTEXT_ITEM ECI, ELEMENT E WHERE ECI.ATTRIBUTE_ID = E.ELEMENT_ID AND ECI.EXPRMT_CONTEXT_ID IN(SELECT EC.EXPRMT_CONTEXT_ID ContextID FROM EXPRMT_CONTEXT EC WHERE EC.EXPERIMENT_ID = ? AND EC.CONTEXT_TYPE = ? AND EC.CONTEXT_NAME = ?)";
	final static String EXPERIMENT_RESULTS = "SELECT E.LABEL ResultType FROM EXPRMT_MEASURE EM INNER JOIN ELEMENT E ON EM.RESULT_TYPE_ID = E.ELEMENT_ID WHERE EM.EXPERIMENT_ID = ?";
	final static String EXPERIMENT_DOCUMENT = "SELECT DOCUMENT_NAME as Name, DOCUMENT_CONTENT as Content FROM EXPERIMENT_DOCUMENT WHERE EXPERIMENT_ID = ? AND LOWER(DOCUMENT_TYPE) = ?";
}
