package common

class ProjectQueries {
	final static String PROJECT_SUMMARY_BYID = "SELECT P.PROJECT_ID AS PID, P.PROJECT_STATUS AS Status, P.PROJECT_NAME AS Name, P.DESCRIPTION Description, to_char(P.DATE_CREATED, 'MM/DD/YYYY') AS DateCreated, to_char(P.LAST_UPDATED, 'MM/DD/YYYY') AS LastUpdated, P.MODIFIED_BY AS ModifiedBy FROM PROJECT P WHERE P.PROJECT_ID = ?";
	String PROJECT_SUMMARY_BYNAME = "SELECT P.PROJECT_ID pid, P.PROJECT_NAME pname, P.GROUP_TYPE pgroup, P.DESCRIPTION pdesc, P.READY_FOR_EXTRACTION ready, P.VERSION pversion, P.PROJECT_STATUS pstatus FROM PROJECT P WHERE P.PROJECT_NAME LIKE ?";
	String PROJECT_SEARCH_COUNT = "SELECT COUNT(P.PROJECT_NAME) pcount FROM PROJECT P WHERE P.PROJECT_NAME LIKE ?";
	final static String PROJECT_CONTEXT_ITEMS = "SELECT E.LABEL AttributeLabel, PCI.VALUE_DISPLAY ValueDisplay FROM PROJECT_CONTEXT_ITEM PCI, ELEMENT E WHERE PCI.ATTRIBUTE_ID = E.ELEMENT_ID AND PCI.PROJECT_CONTEXT_ID IN(SELECT PC.PROJECT_CONTEXT_ID ContextID FROM PROJECT_CONTEXT PC WHERE PC.PROJECT_ID = ? AND PC.CONTEXT_GROUP is null AND PC.CONTEXT_NAME = ?)";
	final static String PROJECT_DOCUMENT = "SELECT DOCUMENT_NAME as Name, DOCUMENT_CONTENT as Content FROM PROJECT_DOCUMENT WHERE PROJECT_ID = ? AND LOWER(DOCUMENT_TYPE) = ?";
}
