ALTER TABLE ASSAY ADD APPROVED_BY VARCHAR2(40);
ALTER TABLE ASSAY ADD APPROVED_DATE TIMESTAMP(6);
ALTER TABLE PROJECT ADD APPROVED_BY VARCHAR2(40);
ALTER TABLE PROJECT ADD APPROVED_DATE TIMESTAMP(6);
ALTER TABLE EXPERIMENT ADD APPROVED_BY VARCHAR2(40);
ALTER TABLE EXPERIMENT ADD APPROVED_DATE TIMESTAMP(6);