-- SCRIPT TO INSERT BAO data into the Element table
--
--  schatwin
--  4/18/12
--
-- commit every 10 rows to isolate any failures
-- based on .obo file v9 from RDM team
--
-- NOTE: this does not increment the sequences.
--  they should be ALTERed to reset the start number


insert into element (element_id, parent_element_id,label, description, element_status_id) values (0, '', 'BARD ASSAY ONTOLOGY', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (1, '', 'BARD DICTIONARY', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (2, '', 'EXTERNAL DICTIONARY', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (3, '', 'EXTERNAL ONTOLOGY', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (4, 0, 'assay', 'An experiment carried out to test the effect of a perturbagen on a biological entity, measuring one or more readout facilitated by an assay design and assay type, and record the results one or more endpoint that quantifies or qualifies the extent of perturbation.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (5, 0, 'biology', 'A biological entity or process that is the presumed subject of the assay; may refer to a macromolecule whose activity is being regulated, or to a cell-biological process (e.g., neurite outgrowth).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (6, 0, 'project management', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (7, 0, 'result', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (303, 1, 'assay kit name', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (304, 1, 'cell line name (SEED FROM ATCC)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (305, 1, 'primary cell name', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (306, 1, 'detection instrument', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (289, 2, 'molecular entity', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (286, 3, 'GO', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (287, 3, 'GO', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (288, 3, 'DO', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (8, 4, 'assay component', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (9, 4, 'assay component role', 'A role associated with an assay component.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (10, 4, 'assay design', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (11, 4, 'assay measure group', 'An abstract concept to group multiple assay readouts and allow description of an assay that measures more than one effect of a perturbagen on the biological entity.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (12, 4, 'assay type', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (13, 5, 'molecular target', 'A biological entity that has the role of target of an assay; usually a biological macromolecule that interacts with a perturbagen to produce the readout detected by the assay.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (14, 5, 'biological process (EXTERNAL ONTOLOGY)', 'Gene Ontology', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (17, 6, 'assay instance', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (18, 6, 'depositor information', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (19, 6, 'project information', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (215, 6, 'assay panel information', 'An abstract concept to group multiple assay instances and allow description of a group of assays that measure more than one effect of a perturbagen directed at prioritization by viewing the results together (e.g., a selectivity panel of assays for activity against each member of a family of related proteins).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (249, 7, 'endpoint', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (250, 7, 'result detail', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (308, 306, 'FACS', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (309, 306, 'microscope', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (310, 306, 'plate-reader', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (311, 306, 'plate-scanner', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (290, 289, 'molecular entity identifier', 'An external database unique identifier, such as an accession number, for a gene or protein from a trusted international source (e.g., Entrez, UniProt).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (291, 289, 'molecular entity identifier source', 'A trusted international source (e.g., Entrez, UniProt) of gene or protein names.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (292, 289, 'molecular entity name', 'A short symbol or name for a gene or protein from a trusted international source (e.g., Entrez, UniProt).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (293, 289, 'molecular entity species', 'A formal name in binomial nomenclature for the species of origin for a gene or protein.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (294, 289, 'molecular entity description', 'A long name for a gene or protein from a trusted international source (e.g., Entrez, UniProt).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (295, 289, 'molecular entity type', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (20, 8, 'assay kit', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (21, 8, 'assay reagent', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (22, 8, 'biological entity', 'A material entity of biological origin (e.g., protein, cell culture, tissue).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (25, 8, 'small molecule', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (26, 9, 'control role', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (27, 9, 'detector role', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (28, 9, 'receiver role', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (29, 9, 'modulator role', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (30, 9, 'reagent role', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (84, 10, 'assay format', 'A concept of an assay based on the biological or chemical features of the assay components, including biochemical assays with purified protein, cell-based assays performed whole cells, and organism-based assays performed in an organism.', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (85, 10, 'assay parameter', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (86, 10, 'detection instrument (BARD DICTIONARY)', 'The category and model name of equipment used for measurement of the readout of an assay (e.g., ViewLux microtiter plate reader).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (87, 10, 'detection method', 'A physical method (technology) used to measure one or more readout of the effect caused by a perturbagen in the assay.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (103, 10, 'assay method', 'The underlying method (technology) and assay strategy used to determine the action of the perturbagen in the assay system.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (124, 11, 'measure group name', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (125, 11, 'assay readout ID', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (143, 12, 'molecular interaction assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (144, 12, 'binding assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (145, 12, 'cell morphology assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (146, 12, 'cell motility assay', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (147, 12, 'toxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (148, 12, 'enzyme activity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (149, 12, 'gene-expression assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (150, 12, 'membrane potential assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (151, 12, 'physico-chemical property determination assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (152, 12, 'protein-folding assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (153, 12, 'protein turnover assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (154, 12, 'RNA splicing assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (155, 12, 're-distribution assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (157, 12, 'signal transduction assay', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (158, 12, 'transporter assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (159, 12, 'viability assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (196, 12, 'safety pharmacology assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (200, 12, 'organism assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (207, 12, 'cell communication assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (208, 12, 'cell cycle assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (209, 12, 'cell growth assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (210, 12, 'cellular metabolic process assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (211, 12, 'coagulation assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (212, 12, 'development assay', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (213, 12, 'multi-organism process assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (214, 12, 'system process assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (15, 13, 'molecular entity (EXTERNAL DICTIONARY)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (16, 13, 'molecular function (EXTERNAL ONTOLOGY)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (23, 17, 'perturbagen collection', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (218, 17, 'assay ID', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (222, 17, 'assay stage', 'A description of the purpose of an assay within a project; relates to the order of assays in a screening campaign (e.g., a primary assay is performed first to identify hits, which are then confirmed in a confirmatory assay, after which secondary assays further prioritize confirmed hits).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (240, 18, 'depositor laboratory', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (241, 18, 'deposition date', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (242, 19, 'biological project goal', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (243, 19, 'screening campaign', 'A concept to group multiple assay instances whose sequential performance is used to identify active pertubagens with a specific function and establish mode-of-action; usally progresses through primary assay, confirmatory assays, secondary assays, and lead-optimization assays.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (273, 19, 'project name', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (216, 215, 'assay instance ID', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (217, 215, 'assay panel name', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (254, 249, 'concentration endpoint', 'An endpoint expressed as a concentration at which a perturbagen mediates a ined response (e.g., IC50, EC50); always has one value in units of molar concentration.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (255, 249, 'biochemical constant endpoint', 'An endpoint used to express binding constants or enzyme kinetic constants reflecting interactions between ligands and macromolecules (e.g., Bmax, Kd).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (256, 249, 'response endpoint', 'An endpoint reporting the magnitude or relative magnitude of effect induced by a perturbagen; often expressed relative to control measurements.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (257, 249, 'temperature endpoint', 'An endpoint that reports a change in temperature as a measure of the extent of perturbation (e.g., Tm).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (260, 249, 'profile endpoint', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (251, 250, 'curve-fit specification', 'A descripition of curve-fit parameters used to obtain an endpoint by fitting a single function across a range of measurements; contains information about curve-fit parameters, methods, properties (e.g., Hill coefficient), concentration range, and replicates.', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (252, 250, 'normalization method', 'A description of a data normalization method (e.g., normalized percent distribution, Z-score, B-score) used to correct raw data for inference errors (i.e., false negatives and false positives), especially after testing at a single concentration or with a small number of replicates.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (253, 250, 'endpoint mode-of-action', 'A description of the qualitative effect of a perturbagen in an assay (e.g., inhibition, activation, cytotoxicity).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (104, 309, 'MDS IX Micro', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (105, 309, 'MDS IX Ultra', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (106, 309, 'Perkin Elmer Operetta', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (312, 310, 'Perkin Elmer Enspire', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (313, 310, 'Perkin Elmer Envision', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (314, 310, 'Perkin Elmer Viewlux', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (315, 310, 'Thermo Fisher VarioSkan', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (316, 311, 'TTP Labtech Acumen', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (296, 295, 'protein', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (297, 295, 'DNA', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (298, 295, 'RNA', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (299, 20, 'assay kit name (BARD DICTIONARY)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (31, 22, 'biological fluid', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (33, 22, 'nucleic acid', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (34, 22, 'organ', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (35, 22, 'organism', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (37, 22, 'protein', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (38, 22, 'tissue', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (266, 22, 'cultured cell', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (39, 26, 'negative control', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (40, 26, 'positive control', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (332, 26, 'high control', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (333, 26, 'low control', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (334, 26, 'background control', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (41, 27, 'analyte', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (42, 27, 'dye', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (43, 27, 'measured component', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (44, 27, 'radioisotope label', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (47, 27, 'tracer', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (45, 28, 'receptor', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (68, 28, 'target', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (48, 29, 'cytokine', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (49, 29, 'attractant', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (50, 29, 'differentiation agent', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (52, 29, 'growth factor', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (56, 29, 'sensitizer', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (61, 29, 'blocker', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (62, 29, 'inducer', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (64, 29, 'ligand', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (65, 29, 'modulator', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (66, 29, 'mutagen', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (67, 29, 'perturbagen', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (46, 30, 'substrate', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (51, 30, 'solvent', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (53, 30, 'growth medium', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (54, 30, 'media component', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (57, 30, 'transfection agent', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (69, 30, 'buffer', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (70, 30, 'carrier', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (71, 30, 'charge carrier', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (72, 30, 'co-enzyme', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (73, 30, 'co-factor', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (74, 30, 'co-substrate', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (75, 30, 'coupled enzyme', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (76, 30, 'cross-linker', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (77, 30, 'de-polarizer', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (78, 30, 'detergent', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (79, 30, 'fixative', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (80, 30, 'ionophore', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (81, 30, 'reducing agent', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (82, 30, 'solute', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (83, 30, 'vehicle', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (88, 84, 'biochemical format', 'An in vitro format used to measure the activity of a biological macromolecule, either purified protein or nucleic acid; most often a homogenous assay format, but can be heterogeneous if a solid phase (e.g. beads) is used to immobilize the macromolecule.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (89, 84, 'cell-based format', 'A heterogenous assay format that involves living cells of eukaryotic origin.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (90, 84, 'cell-free format', 'An in vitro format where biological material originates from cells, but does not use live cells nor purified macromolecules; most often a homogenous assay format, but can be heterogeneous if a solid phase (e.g. beads) is used to immobilize the components.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (91, 84, 'organism-based format', 'A heterogenous assay format that involves living organisms.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (92, 84, 'tissue-based format', 'A heterogenous assay format that involves tissue derived from a living organism.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (107, 85, 'biological parameter', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (108, 85, 'chemical parameter', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (109, 85, 'mechanical parameter', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (97, 87, 'fluorescence method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (98, 87, 'imaging method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (99, 87, 'label-free method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (100, 87, 'luminescence method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (101, 87, 'radiometry method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (102, 87, 'spectrophotometry method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (335, 103, 'method by function', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (336, 103, 'method by physical basis', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (160, 143, 'protein-DNA interaction assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (161, 143, 'protein-RNA interaction assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (162, 143, 'protein-protein interaction assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (163, 143, 'protein-small molecule interaction assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (179, 147, 'acute toxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (180, 147, 'carcinogenicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (181, 147, 'cell-proliferation assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (182, 147, 'clinical pathology assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (183, 147, 'cytotoxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (184, 147, 'dermal toxicity assay', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (185, 147, 'developmental toxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (186, 147, 'endocrine disruption assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (187, 147, 'genotoxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (188, 147, 'immune-response assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (189, 147, 'inhalation toxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (190, 147, 'neurotoxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (191, 147, 'ocular toxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (192, 147, 'oxidative stress assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (193, 147, 'phototoxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (194, 147, 'repeat-dose toxicity assay', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (195, 147, 'reproductive toxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (178, 150, 'ion-channel assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (171, 151, 'acid-ionization constant determination assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (172, 151, 'identification assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (173, 151, 'lipophilicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (174, 151, 'melting-point determination assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (175, 151, 'purity determination assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (176, 151, 'solubility assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (177, 151, 'stability assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (206, 151, 'concentration determination assay', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (164, 157, 'cytokine secretion assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (165, 157, 'post-translational modification assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (166, 157, 'reporter-gene assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (167, 157, 'second messenger assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (197, 196, 'drug abuse assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (198, 196, 'drug-interaction assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (199, 196, 'QT interval assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (201, 200, 'behavioral assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (202, 200, 'metastasis assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (203, 200, 'pharmacodynamic assay', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (204, 200, 'pharmacokinetic assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (205, 200, 'therapeutic efficacy assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (24, 23, 'RNA construct collection', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (140, 23, 'perturbagen delivery', 'A description of whether perturbagens are tested individually or as pooled mixtures.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (141, 23, 'small-molecule collection', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (223, 222, 'confirmatory assay', 'An assay performed to confirm activity of perturbagens identified in a primary assay; may be performed as replicate measurements or as a concentration-response assay.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (224, 222, 'lead-optimization assay', 'An assay performed in the lead-optimization stage on a relatively small number of active perturbagens; typically a high-quality concentration-response assay.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (225, 222, 'primary assay', 'An assay performed (usually first in a campaign) to identify potentially biologically active pertubagens; usually performed at a single concentration with one or two measurements.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (226, 222, 'secondary assay', 'An assay performed following a confirmatory assay to confirm the biological activity a perturbagen using a different assay type or design; may address mode-of-action, toxicity, activity profile, and selectivity.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (246, 242, 'intended mode-of-action', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (247, 242, 'intended molecular target', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (248, 242, 'disease', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (244, 243, 'screening campaign name', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (245, 243, 'assay instance ID', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (340, 254, 'IC50', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (258, 255, 'binding constant', 'This endpoint type describes the bonding affinity between two molecules at equilibrium, e.g., drug-receptor interaction.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (259, 255, 'enzyme kinetic constant', 'Describe kinetics of enzyme-catalyzed reactions. It includes the enzyme kinetic constants namely, Km and Vmax, which help to model the time course of disappearance of substrate and the production of product.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (339, 256, 'percent inhibition', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (341, 257, 'Tm', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (261, 260, 'gene-expression profile', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (262, 260, 'panel-assay profile', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (263, 260, 'computational profile', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (264, 33, 'DNA', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (265, 33, 'RNA', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (285, 37, 'molecular entity (EXTERNAL DICTIONARY)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (32, 266, 'cell line', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (36, 266, 'primary cell', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (93, 88, 'nucleic acid format', 'A format in which the perturbagen targets nucleic acid (DNA or RNA) to regulate its function.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (94, 88, 'protein format', 'A format in which the perturbagen targets a protein to regulate its function.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (95, 90, 'sub-cellular format', 'A format using sub-cellular organelles (but not individually purified proteins) obtained by cell lysis and fractionation (e.g., differential centrifugation).', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (96, 90, 'whole-cell lysate format', 'A format using cells whose membranes have been ruptured (e.g., mechanically, osmotically) and whose lysate is used without separation techniques.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (126, 107, 'cell attribute', 'This describes the cell culture conditions and modifications performed on the cell line. Modifications include plasmid transfection, viral transduction, cell fusion, etc.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (127, 107, 'protein attribute', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (280, 107, 'DNA construct attribute', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (110, 109, 'assay biosafety level', 'A biosafety level is the level of biocontainment required to isolate hazardous biological agents in an enclosed facility. The levels of containment range from the lowest biosafety level of 1 to the highest at level 4.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (111, 109, 'assay condition', 'A set of optimization guidelines used to minimize the time and cost of assay implementation, while providing reliable assay performance.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (112, 109, 'assay footprint', 'This describes the physical format such as plate density in which an assay is performed, which is generally a microplate format, but can also be an array format.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (113, 109, 'assay measurement throughput', 'Assay measurements throughput quality describes the quality of the measurements performed on each sample, such as single concentration, single repetition, concentration-response, multiple repetitions, etc.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (114, 109, 'assay quality assessment', 'Commonly used statistical parameters for monitoring assay quality include Z and Z-prime factors. Prior to starting a large screen, and after assay optimization and miniaturization, pilot screens are performed to assess the quality of the assay run and to assess / validate the suitability of a assay for a high-throughput screening run.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (115, 109, 'assay readout content', 'This describes the throughput and information content generated. Categorizing multiplexed (i.e. multiple targets measured simultaneously) and multiparametric assays and high content (image-based) and regular (plate reader) assays.', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (120, 109, 'assay measurement type', 'This describes whether a change in an assay is measured once at one fixed end-point or over a period of time at several time points.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (121, 109, 'signal direction', 'It is the trend of measured readout signal, whether it increases or decreases in perturbagen treated wells, as compared to the untreated or carrier-treated wells in an assay.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (122, 109, 'unit of measurement', 'It is the inite magnitude of a physical quantity or of time. It has a quantity and a unit associated with it.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (123, 109, 'wavelength', 'For fluorescence measurements, it is the wavelength at which the fluorophore is excited and the wavelength at which it emits fluorescence. In the case of absorbance, it is the wavelength at which light is absorbed by a biological entity or a dye.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (331, 109, 'assay phase characteristic', 'It refers to whether all the assay components are in solution or some are in solid phase, which determines their ability to scatter light.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (337, 335, 'amplification method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (338, 336, 'radiation based method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (168, 165, 'phosphorylation assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (169, 165, 'methylation assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (170, 165, 'acetylation assay', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (267, 24, 'RNA construct collection name', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (268, 24, 'RNA construct perturbagen', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (139, 141, 'small-molecule perturbagen', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (221, 141, 'small-molecule collection name', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (276, 141, 'small-molecule collection source', 'A description of whether a small-molecule collection was purchased from a vendor or generated in an academic institution.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (227, 226, 'alternate confirmatory assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (228, 226, 'counter-screening assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (229, 226, 'selectivity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (277, 247, 'molecular entity', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (278, 247, 'molecular function', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (342, 258, 'Bmax', 'It is the amount of drug required to saturate a population of receptors and a measure of the number of receptors present in the sample. It is derived from Scatchard plot of binding data. It is analogous to Vmax in enzyme kinetics. The units of Bmax include cpm, sites/cell or fmol/mg. http', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (343, 259, 'Vmax', 'Vmax is ined as the maximum initial velocity of an enzyme catalyzed reaction under the given conditions, and it is measured in units of quantity of substrate transformed per unit time for a given concentration of enzyme.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (283, 264, 'molecular entity (EXTERNAL DICTIONARY)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (284, 265, 'molecular entity (EXTERNAL DICTIONARY)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (300, 32, 'cell line name (BARD DICTIONARY)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (301, 36, 'primary cell name (BARD DICTIONARY)', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (128, 126, 'cell culture condition', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (129, 126, 'cell modification', 'This describes the type of alterations performed on the cell line, which include plasmid transfection, viral transduction, cell fusion, etc.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (324, 126, 'cell line culturing', 'This describes the growth mode of a cell line, whether it grows attached to the culture dish (adherent) or floating (suspension) in the culture medium or partially attached (mixed adherent and suspension).', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (135, 127, 'protein form', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (136, 127, 'protein preparation method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (137, 127, 'protein purity', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (317, 127, 'protein ID', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (318, 127, 'organism', 'The organism form which the protein was obtained.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (281, 280, 'construct form', 'It describes whether the gene that is inserted in the construct is wild type or mutated, truncated, etc.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (282, 280, 'gene ID', 'Gene ID of the gene inserted in the construct.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (302, 280, 'DNA construct', 'A brief description of the recombinant DNA created by the insertion of a gene or siRNA of interest into a vector. It includes information on the type of vector, the type of promoter, the selectable markers, etc., which are all considered when sub-cloning a gene of interest. The construct is transfected into cells by various methods.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (307, 280, 'organism', 'The species information of the gene that was inserted in the construct .', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (319, 280, 'gene name', 'Standard name of the gene that was inserted in the DNA construct.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (320, 280, 'reporter gene', 'A reporter gene is a gene that is attached to a regulatory sequence of another gene of interest and introduced into cultured cells, animals or plants. Certain genes function as reporters because they are easily identified and measured, or because they are selectable markers. Common reporter genes are luciferase, green fluorescent protein (GFP), beta-galactosidase and chloramphenicol acetyltransferase (CAT).', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (321, 280, 'reporter gene ID', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (322, 280, 'regulatory region', 'The name of the promoter or artificial regulatory element that was inserted upstream of the reporter gene.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (323, 280, 'vector name', 'A vector is an extrachromosomal, self-replicating DNA molecule that is used as a vehicle to transfer the DNA of interest into cells, e.g.,plasmid vector (pGEM-T, pBluescript), lentiviral vector, retroviral vector, etc.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (116, 111, 'incubation time', 'An interval of time between the addition of pertubagen, substrate, or cell modification, and the measurement of change using the detection method of the assay.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (117, 111, 'pressure', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (118, 111, 'temperature', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (119, 111, 'pH', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (329, 120, 'endpoint assay', 'In this assay, change in activity is measured at one time point.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (330, 120, 'kinetic assay', 'In this assay, change in activity is measured at several time points over a period of time.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (269, 268, 'RNA construct type', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (270, 268, 'RNA construct identifier', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (271, 268, 'RNA construct source', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (272, 268, 'RNA construct sequence', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (142, 139, 'small-molecule source', 'A description of whether a small molecule was purified from a natural source or synthesized.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (219, 139, 'small-molecule identifier', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (220, 139, 'small-molecule structure', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (230, 227, 'alternate assay components', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (231, 227, 'alternate assay format', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (232, 227, 'alternate assay type', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (233, 227, 'orthogonal assay design', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (234, 227, 'orthogonal assay detection method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (279, 227, 'alternate assay parameters', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (235, 228, 'alternate target assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (236, 228, 'compound toxicity assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (237, 228, 'parental cell line assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (238, 228, 'physiochemical assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (239, 228, 'construct variant assay', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (130, 128, 'cell culture component', 'This describes the specific medium in which a cell line is cultured, which is optimized for its growth. It includes the medium additives namely, serum, growth factors, buffers, amino acids, antibiotics, etc. This information can be obtained from ATCC or found in relevant publications.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (131, 128, 'passage number', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (132, 128, 'number of cells', '', 2);
COMMIT;
insert into element (element_id, parent_element_id,label, description, element_status_id) values (133, 129, 'transfection method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (134, 129, 'fixation method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (138, 129, 'infection method', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (274, 269, 'shRNA', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (275, 269, 'siRNA', '', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (325, 130, 'assay medium', 'The cell culture broth used while performing an assay on cells, which is optimized for each assay type. Some interfering additives such as serum, growth factors, buffers, amino acids, antibiotics, etc. might be eliminated in this medium.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (326, 130, 'assay serum', 'The serum used in assay medium while performing an assay on cells and is optimized for each assay type. In certain assays, the cells could be maintained at either a lower concentration of the serum used in regular culture or in a specialized serum, including dextran charcoal treated serum, dialyzed serum, etc. This is done to avoid interference with the assay measurements.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (327, 130, 'culture serum', 'Cultured cells require serum or growth factors for growth by cell division. Each cell type is grown in a medium supplemented with a variable concentration of serum (up to 20%) which is optimized for its growth. Specialized sera include dextran charcoal treated serum, which lacks certain hormones, growth factors, etc, dialyzed serum, which lacks low molecular weight molecules (below 10,000 MW), such as glucose, amino acids, low molecular weight hormones, cytokines, etc. These sera are used in certain assays to avoid interference from the normal serum components. Most commonly, fetal bovine serum is used in cell culture, but other sera such as horse serum are also used.', 2);
insert into element (element_id, parent_element_id,label, description, element_status_id) values (328, 130, 'culture medium', 'The liquid broth used to grow cells, which is optimized for each cell type and includes additives such as growth factors, buffers, amino acids, antibiotics, etc. This information can be obtained from ATCC or found in relevant publications.', 2);
commit;

-- SCRIPT TO INSERT BAO results into the result type table
--
--  schatwin
--  4/18/12
--
-- commit every 10 rows to isolate any failures
--
--

insert into result_type
(RESULT_TYPE_ID,
    PARENT_RESULT_TYPE_ID,
    RESULT_TYPE_NAME,
    DESCRIPTION,
    RESULT_TYPE_STATUS_ID,
    BASE_UNIT)
select element_ID,
    decode(element_ID,7,null,parent_element_id),
    label,
    DESCRIPTION,
    element_STATUS_ID,
    null 
from element
connect by parent_element_id = prior element_id
start with element_Id = 7;
commit;
