ALTER TABLE MEASURE_CONTEXT_ITEM ADD EXT_VALUE_ID VARCHAR2(60) NULL ;

ALTER TABLE MEASURE_CONTEXT_ITEM MODIFY (VALUE_DISPLAY VARCHAR2(500));

DROP INDEX AK_MEASURE_CONTEXT_ITEM;
CREATE UNIQUE INDEX AK_MEASURE_CONTEXT_ITEM ON MEASURE_CONTEXT_ITEM
(
  ASSAY_ID,
  MEASURE_CONTEXT_ID,
  GROUP_MEASURE_CONTEXT_ITEM_ID,
  ATTRIBUTE_ID,
  ATTRIBUTE_TYPE,
  VALUE_DISPLAY
);

ALTER TABLE RESULT_CONTEXT_ITEM ADD CONSTRAINT CK_RESULT_CONTEXT_ITEM_NULL
CHECK (EXPERIMENT_ID IS NOT NULL OR RESULT_ID IS NOT NULL);

ALTER TABLE EXTERNAL_REFERENCE DROP CONSTRAINT FK_EXT_REFERENCE_EXT_SYTEM;

ALTER TABLE EXTERNAL_REFERENCE ADD CONSTRAINT FK_EXT_REFERENCE_EXT_SYSTEM
FOREIGN KEY (EXTERNAL_SYSTEM_ID) REFERENCES EXTERNAL_SYSTEM (EXTERNAL_SYSTEM_ID) ENABLE VALIDATE;