ALTER TABLE EXPRMT_MEASURE ADD RESULT_TYPE_ID NUMBER(19);
ALTER TABLE EXPRMT_MEASURE ADD STATS_MODIFIER_ID NUMBER(19);


CREATE INDEX FK_EXP_MEASURE_RESULT_TYPE
    ON EXPRMT_MEASURE(RESULT_TYPE_ID)
;
CREATE INDEX FK_EXP_MEASURE_STATS_MOD
    ON EXPRMT_MEASURE(STATS_MODIFIER_ID)
;

ALTER TABLE EXPRMT_MEASURE ADD CONSTRAINT FK_EXP_MEASURE_RESULT_TYPE
FOREIGN KEY (RESULT_TYPE_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
ALTER TABLE EXPRMT_MEASURE ADD CONSTRAINT FK_EXP_MEASURE_STATS_MOD
FOREIGN KEY (STATS_MODIFIER_ID)
REFERENCES ELEMENT (ELEMENT_ID)
ENABLE VALIDATE
;
