CREATE TABLE ASSAY_CTXT_EXP_MEASURE
(
    ASSAY_CTXT_EXP_MEASURE_ID NUMBER(19)   NOT NULL,
    ASSAY_CONTEXT_ID         NUMBER(19)   NOT NULL,
    EXPERIMENT_MEASURE_ID               NUMBER(19)   NOT NULL,
    VERSION                  NUMBER(38)   DEFAULT 0 NOT NULL,
    DATE_CREATED             TIMESTAMP(6) DEFAULT sysdate NOT NULL,
    LAST_UPDATED             TIMESTAMP(6) DEFAULT sysdate NOT NULL,
    MODIFIED_BY              VARCHAR2(40)     NULL
)
;
CREATE SEQUENCE assay_ctxt_exp_measure_ID_SEQ
    START WITH 1
    INCREMENT BY 1
    NOMINVALUE
    MAXVALUE 2147483648
    NOCYCLE
    CACHE 20
    NOORDER
;
ALTER TABLE ASSAY_CTXT_EXP_MEASURE
    ADD CONSTRAINT PK_ASSAY_CTXT_EXP_MEASURE
    PRIMARY KEY (ASSAY_CTXT_EXP_MEASURE_ID)
    USING INDEX STORAGE(BUFFER_POOL DEFAULT)
    ENABLE
    VALIDATE
;
CREATE INDEX FK_ECM_ASSAY_CONTEXT
    ON ASSAY_CTXT_EXP_MEASURE(ASSAY_CONTEXT_ID)
;
CREATE INDEX FK_ECM_MEASURE
    ON ASSAY_CTXT_EXP_MEASURE(EXPERIMENT_MEASURE_ID)
;
ALTER TABLE ASSAY_CTXT_EXP_MEASURE
    ADD CONSTRAINT FK_ECM_ASSAY_CONTEXT
FOREIGN KEY (ASSAY_CONTEXT_ID)
REFERENCES ASSAY_CONTEXT (ASSAY_CONTEXT_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
ALTER TABLE ASSAY_CTXT_EXP_MEASURE
    ADD CONSTRAINT FK_ECM_MEASURE
FOREIGN KEY (EXPERIMENT_MEASURE_ID)
REFERENCES EXPRMT_MEASURE (EXPRMT_MEASURE_ID)
ON DELETE CASCADE
ENABLE VALIDATE
;
