ALTER TABLE EXPRMT_MEASURE DROP COLUMN MEASURE_ID;
--DROP TABLE ASSAY_CONTEXT_MEASURE PURGE;
--DROP TABLE MEASURE PURGE;
ALTER TABLE EXPRMT_MEASURE ADD CONSTRAINT CK_EXPM_RESULT_TYPE_ID CHECK (RESULT_TYPE_ID IS NOT NULL)

