ALTER TABLE ELEMENT DROP CONSTRAINT CK_ELEMENT_EXTRACTION
;
ALTER TABLE ELEMENT ADD CONSTRAINT CK_ELEMENT_EXTRACTION
CHECK (ready_for_extraction IN ('Not Ready', 'Ready', 'Started', 'Complete', 'Failed'))
;
ALTER TABLE EXPERIMENT DROP CONSTRAINT CK_EXPERIMENT_EXTRACTION
;
ALTER TABLE EXPERIMENT ADD CONSTRAINT CK_EXPERIMENT_EXTRACTION
CHECK (ready_for_extraction IN ('Not Ready', 'Ready', 'Started', 'Complete', 'Failed'))
;
ALTER TABLE PROJECT DROP CONSTRAINT CK_PROJECT_EXTRACTION
;
ALTER TABLE PROJECT ADD CONSTRAINT CK_PROJECT_EXTRACTION
CHECK (ready_for_extraction IN ('Not Ready', 'Ready', 'Started', 'Complete', 'Failed'))
;
ALTER TABLE ASSAY DROP CONSTRAINT CK_ASSAY_EXTRACTION
;
ALTER TABLE ASSAY ADD CONSTRAINT CK_ASSAY_EXTRACTION
CHECK (ready_for_extraction IN ('Not Ready', 'Ready', 'Started', 'Complete', 'Failed'))
;
