/*
 * File: app/view/CapApp.js
 * Date: Fri Apr 20 2012 15:40:50 GMT-0400 (Eastern Daylight Time)
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('BARD.view.CapApp', {
    extend: 'Ext.container.Viewport',
    requires: [
        'BARD.view.AssayForm',
        'BARD.view.ResultTypesForm'
    ],

    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    title: 'CAP Assay Definition',
                    activeTab: 1,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Find an Assay'
                        },
                        {
                            xtype: 'panel',
                            width: 983,
                            title: 'Extract Name, Description',
                            items: [
                                {
                                    xtype: 'assayform'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            title: 'Result Types (Measures)',
                            items: [
                                {
                                    xtype: 'resulttypesform'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});